name: value-object
description: |
  Generate a DDD value object with branded type, Zod validation, and factory functions.

  Generates a TypeScript module with:
  - Branded type for compile-time safety
  - Zod validation schema
  - Factory function returning Result type
  - Type guard function
  - Unsafe factory for trusted inputs

  Time saved: 15-25 min → 1 min

version: 1.0.0

variables:
  name:
    type: string
    description: Value object name (PascalCase — e.g., 'Email', 'Slug', 'PhoneNumber')
    required: true
    position: 0
    prompt: What is the value object name? (PascalCase, e.g., 'Email', 'Slug')

  baseType:
    type: enum
    values: ['string', 'number', 'bigint']
    default: 'string'
    description: The underlying primitive type

  validation:
    type: string
    description: Validation rules description (e.g., "must be valid email format", "3-50 chars, lowercase, hyphens only")
    required: false

onSuccess: |
  Value object '{{ name }}' generated successfully!

  Generated files:
    lib/domain/value-objects/{{ name }}.ts

  Usage:
    import { create{{ name }}, is{{ name }}, type {{ name }} } from '@/lib/domain/value-objects/{{ name }}'
    const result = create{{ name }}('value')
    if (result.success) { /* result.data is {{ name }} */ }

steps:
  - name: Generate value object
    tool: template
    template: templates/value-object.ts.jig
