name: scroll-to-top
description: Add scroll-to-top button to your Starlight site
version: "1.0.0"

variables:
  projectFolder:
    type: string
    description: Project folder path
    default: "."

steps:
  - name: Install starlight-scroll-to-top
    tool: shell
    command: |
      cd "{{ projectFolder }}" && bun add starlight-scroll-to-top

onSuccess: |
  ✅ Scroll-to-top button added!
