name: entity
description: |
  Generate a domain entity with ORM schema, Zod validation, and TypeScript types.

  Generates:
  - Zod validation schema with create/update variants and inferred types
  - Drizzle table definition (when ORM is Drizzle)
  - Prisma model injection (when ORM is Prisma)
  - Schema barrel export (when ORM is Drizzle)

  Time saved: 20-40 min → 2 min

version: 1.0.0

variables:
  name:
    type: string
    description: Entity name (singular, camelCase — e.g., 'user', 'organization', 'todoItem')
    required: true
    position: 0
    prompt: What is the entity name? (singular, e.g., 'user', 'organization')

  fields:
    type: string
    description: Comma-separated fields with types (e.g., "name:string,email:string,role:enum")
    required: false
    prompt: |
      Enter fields (comma-separated, format: name:type)
      Leave empty for AI to infer from entity name
      Example: name:string,email:string,isActive:boolean

  relations:
    type: string
    description: Comma-separated relations (e.g., "belongsTo:organization,hasMany:todos")
    required: false

  withRepository:
    type: boolean
    description: Also generate a repository interface and ORM implementation
    default: false

onSuccess: |
  Entity '{{ name }}' generated successfully!

  Generated files:
    lib/schemas/{{ name }}-schema.ts -- Zod validation + types
  @if(detectedOrm === 'drizzle')
    db/schema/{{ name }}.ts -- Drizzle table definition
    db/schema/index.ts -- Updated barrel export
  @elseif(detectedOrm === 'prisma')
    prisma/schema.prisma -- Prisma model (injected)
  @end
  @if(withRepository)
    lib/domain/repositories/{{ name }}-repository.ts -- Repository interface
  @if(detectedOrm !== 'none')
    lib/infrastructure/repositories/{{ name }}-repository.impl.ts -- {{ detectedOrm }} implementation
  @end
  @end

  Next steps:
    1. Review the generated schema
    2. Run migrations (drizzle-kit push / prisma db push)
  @if(!withRepository)
    3. Use 'hypergen nextjs domain repository {{ name }}' to add a repository
  @end

steps:
  - name: Detect ORM
    tool: shell
    command: |
      if grep -q '"drizzle-orm"' package.json 2>/dev/null; then
        echo "drizzle"
      elif grep -q '"@prisma/client"' package.json 2>/dev/null; then
        echo "prisma"
      else
        echo "none"
      fi
    exports:
      detectedOrm: "{{ result.stdout.trim() }}"

  - name: Generate Zod validation schema
    tool: template
    template: templates/zod-schema.ts.jig

  - name: Generate Drizzle table definition
    tool: template
    template: templates/drizzle-schema.ts.jig
    when: "detectedOrm === 'drizzle'"

  - name: Generate Prisma model
    tool: template
    template: templates/prisma-schema.prisma.jig
    when: "detectedOrm === 'prisma'"

  - name: Update schema barrel export
    tool: template
    template: templates/schema-index.ts.jig
    when: "detectedOrm === 'drizzle'"

  - name: Generate repository
    tool: recipe
    recipe: ../../repository
    when: "withRepository === true"
    args:
      name: "{{ name }}"

