name: create
description: Create a beautiful Astro/Starlight documentation site with TypeDoc integration
version: 2.0.0
author: "@SubtleTools"

variables:
  projectFolder:
    type: string
    required: false
    description: "Project folder name (where all files will be generated)"
    default: "my-docs-site"
    
  projectName:
    type: string
    required: true
    description: "Project name for the documentation site"
    
  projectDescription:
    type: string
    required: true
    description: "Project description"
    
  siteUrl:
    type: string
    required: false
    description: "Site URL (e.g., https://example.com)"
    default: "https://localhost:4321"
    
  githubRepo:
    type: string
    required: false
    description: "GitHub repository URL (optional)"
    
  enableTypedoc:
    type: boolean
    required: false
    description: "Enable TypeDoc API documentation?"
    default: true
    
  entryPoint:
    type: string
    required: false
    description: "TypeScript entry point for API docs (e.g., src/index.ts)"
    default: "src/index.ts"
    
  enableOpenAPI:
    type: boolean
    required: false
    description: "Enable OpenAPI/Swagger documentation?"
    default: false
    
  enableKeyboardShortcuts:
    type: boolean
    required: false
    description: "Enable keyboard shortcuts documentation (starlight-kbd)?"
    default: false
    
  enableAutoSidebar:
    type: boolean
    required: false
    description: "Enable automatic sidebar generation?"
    default: false
    
  enableScrollToTop:
    type: boolean
    required: false
    description: "Enable scroll-to-top button?"
    default: true
    
  enableChangelogs:
    type: boolean
    required: false
    description: "Enable changelog documentation?"
    default: false
    
  enableObsidian:
    type: boolean
    required: false
    description: "Enable Obsidian vault integration?"
    default: false

steps:
  - name: Generate project README
    tool: template
    template: README.md.ejs.t
    
  - name: Generate package.json
    tool: template
    template: package.json.ejs.t
    
  - name: Generate Astro config
    tool: template
    template: astro.config.mjs.ejs.t
    
  - name: Generate docs config
    tool: template
    template: docs-config.ts.ejs.t
    
  - name: Generate Tailwind config
    tool: template
    template: tailwind.config.mjs.ejs.t
    
  - name: Generate main documentation index
    tool: template
    template: docs-index.mdx.ejs.t
    
  - name: Generate introduction page
    tool: template
    template: docs-introduction.mdx.ejs.t
    
  - name: Generate installation guide
    tool: template
    template: docs-installation.mdx.ejs.t
    
  - name: Generate quick start guide
    tool: template
    template: docs-quick-start.mdx.ejs.t
    
  - name: Generate core features documentation
    tool: template
    template: docs-features-core.mdx.ejs.t
    
  - name: Generate OpenAPI spec
    tool: template
    template: openapi.yaml.ejs.t
    when: "{{ enableOpenAPI }}"
    
  - name: Setup project structure
    tool: action
    action: setup-starlight-project