name: list-page
description: |
  Generate a production-ready list/index page with data table, pagination, search, and filtering.

  Features:
  - Server Component for optimal performance
  - Data table with sorting, filtering, pagination
  - Search functionality
  - Link to create page
  - Auto-detect ORM (Prisma/Drizzle)
  - Responsive design with shadcn/ui

version: 1.0.0

variables:
  name:
    type: string
    description: Resource name (singular, e.g., 'post', 'user', 'product')
    required: true
    prompt: What is the resource name? (singular, e.g., 'post', 'user')
    position: 0

  model:
    type: string
    description: Model name (PascalCase, defaults to capitalized name)
    required: false

  fields:
    type: string
    description: Comma-separated fields with types (e.g., "title:string,content:text,published:boolean")
    required: false
    prompt: |
      Enter fields (comma-separated, format: name:type)
      Leave empty to auto-detect from Prisma/Drizzle schema
      Example: title:string,content:text,published:boolean

  includePagination:
    type: boolean
    description: Include pagination in list view
    default: true

  includeSorting:
    type: boolean
    description: Include sorting in data table
    default: true

  includeFiltering:
    type: boolean
    description: Include filtering in data table
    default: true

steps:
  - name: Generate list page
    tool: template
    template: templates/list-page.tsx.jig

  - name: Generate data table component
    tool: template
    template: templates/table-component.tsx.jig

  - name: Generate Server Actions for list
    tool: template
    template: templates/actions.ts.jig

onSuccess: |
  List page for '{{ name }}' generated successfully!

  Generated files:
    app/{{ name }}/page.tsx - List page
    components/{{ model || name }}Table.tsx - Data table component
    app/actions/{{ name }}.ts - Server Actions for fetching data

  Next steps:
    1. Implement the database query in the Server Action
    2. Customize table columns and styling
    3. Visit /{{ name }} to see your list page
