name: repository
description: |
  Generate a repository interface and ORM-specific implementation for a domain entity.

  Generates:
  - Repository interface with standard CRUD + custom methods
  - Drizzle ORM implementation (when ORM is Drizzle)
  - Prisma implementation (when ORM is Prisma)

  Follows the repository pattern: domain layer defines the interface,
  infrastructure layer provides the implementation.

  Time saved: 30-50 min → 2 min

version: 1.0.0

variables:
  name:
    type: string
    description: Repository name (camelCase entity name — e.g., 'user', 'organization')
    required: true
    position: 0
    prompt: What entity does this repository manage? (e.g., 'user', 'organization')

  entity:
    type: string
    description: Entity name if different from repository name (PascalCase)
    required: false

  methods:
    type: string
    description: Extra methods beyond CRUD (e.g., "findByEmail,findByOrganization,countActive")
    required: false

onSuccess: |
  Repository for '{{ name }}' generated successfully!

  Generated files:
    lib/domain/repositories/{{ name }}-repository.ts -- Interface
  @if(detectedOrm === 'drizzle')
    lib/infrastructure/repositories/{{ name }}-repository.impl.ts -- Drizzle implementation
  @elseif(detectedOrm === 'prisma')
    lib/infrastructure/repositories/{{ name }}-repository.impl.ts -- Prisma implementation
  @end

  Usage:
    import type { {{ pascalCase(name) }}Repository } from '@/lib/domain/repositories/{{ name }}-repository'
  @if(detectedOrm !== 'none')
    import { {{ pascalCase(name) }}RepositoryImpl } from '@/lib/infrastructure/repositories/{{ name }}-repository.impl'
  @end

steps:
  - name: Detect ORM
    tool: shell
    command: |
      if grep -q '"drizzle-orm"' package.json 2>/dev/null; then
        echo "drizzle"
      elif grep -q '"@prisma/client"' package.json 2>/dev/null; then
        echo "prisma"
      else
        echo "none"
      fi
    exports:
      detectedOrm: "{{ result.stdout.trim() }}"

  - name: Generate repository interface
    tool: template
    template: templates/repository-interface.ts.jig

  - name: Generate Drizzle implementation
    tool: template
    template: templates/drizzle-repository.ts.jig
    when: "detectedOrm === 'drizzle'"

  - name: Generate Prisma implementation
    tool: template
    template: templates/prisma-repository.ts.jig
    when: "detectedOrm === 'prisma'"

