name: add
description: |
  Add a React component to a Next.js project.
  Creates a component file with optional "use client" directive.
version: 1.0.0

variables:
  name:
    type: string
    description: Component name in PascalCase (e.g. "UserCard", "NavigationMenu")
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  componentDescription:
    type: string
    description: Brief description of what this component does
    required: true

  dir:
    type: string
    description: Directory relative to project root (e.g. "components", "components/ui", "app/_components")
    default: "components"

  client:
    type: boolean
    description: Add "use client" directive (needed for hooks, event handlers, browser APIs)
    default: false

  withProps:
    type: boolean
    description: Include a typed props interface
    default: true

steps:
  - name: Generate component scaffold
    tool: template
    template: templates/component.tsx.jig

