name: revalidate
description: |
  Generate a Server Action with cache revalidation patterns.
  Includes revalidatePath, revalidateTag, and optimistic update examples.
version: 1.0.0

variables:
  name:
    type: string
    description: Action name in camelCase (e.g. "createPost", "updateUser")
    required: true
    pattern: "^[a-z][a-zA-Z0-9]*$"

  fields:
    type: array
    description: |
      Form fields in format "name:type:validation" (e.g. "title:string:min(5)")
      Supports same format as add-validated recipe
    required: true

  revalidationType:
    type: string
    description: Type of cache revalidation (path, tag, both)
    default: "both"
    enum: ["path", "tag", "both"]

  revalidatePath:
    type: string
    description: Path to revalidate (e.g. "/posts", "/dashboard")
    required: false

  revalidateTags:
    type: array
    description: Cache tags to revalidate (e.g. ["posts", "user-posts"])
    required: false

  dir:
    type: string
    description: Output directory for Server Action
    default: "app/actions"

  schemaDir:
    type: string
    description: Output directory for Zod schema
    default: "lib/schemas"

  withOptimistic:
    type: boolean
    description: Include optimistic update example in documentation
    default: false

  redirectAfter:
    type: boolean
    description: Redirect after successful action
    default: false

  redirectPath:
    type: string
    description: Path to redirect to after success
    required: false

steps:
  - name: Install Zod
    tool: install
    packages: [zod]

  - name: Generate Zod schema
    tool: template
    template: templates/schema.ts.jig

  - name: Generate Server Action
    tool: template
    template: templates/action.ts.jig

onSuccess: |
  Server Action with cache revalidation generated!

  Created files:
    - {{ dir }}/{{ name }}.ts
    - {{ schemaDir }}/{{ kebabCase(name) }}.ts

  Cache revalidation strategy:
  @if(revalidationType === 'path' || revalidationType === 'both')
  @if(revalidatePath)
    Path revalidation: {{ revalidatePath }}
  @else
    Path revalidation enabled (configure in action)
  @end
  @end
  @if(revalidationType === 'tag' || revalidationType === 'both')
  @if(revalidateTags && revalidateTags.length > 0)
    Tag revalidation: {{ revalidateTags.join(', ') }}
  @else
    Tag revalidation enabled (configure in action)
  @end
  @end

  Usage with useActionState:
    import { useActionState } from 'react'
    import { {{ name }} } from '@/{{ dir }}/{{ name }}'

    const [state, formAction] = useActionState({{ name }}, null)
  @if(withOptimistic)

  Optimistic updates:
    import { useOptimistic } from 'react'

    const [optimisticData, addOptimistic] = useOptimistic(
      data,
      (state, newItem) => [...state, newItem]
    )
  @end

  Next.js cache will be automatically revalidated on success.
