name: sortable
description: |
  Generate a TanStack Table with multi-column sorting support.
  Includes sort indicators, click-to-sort headers, and persistent sort state.
version: 1.0.0

variables:
  name:
    type: string
    description: Table component name in PascalCase (e.g. "UsersTable", "ProductsTable")
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  columns:
    type: array
    description: |
      Table columns in format "key:label:type:sortable" (e.g. "id:ID:string:true", "email:Email:string:true")
      Supported types: string, number, boolean, date
      Set sortable to 'true' to enable sorting on that column
    required: true

  dir:
    type: string
    description: Output directory for table component
    default: "components/tables"

  withPagination:
    type: boolean
    description: Include pagination controls
    default: true

  pageSize:
    type: number
    description: Default page size
    default: 10

  multiSort:
    type: boolean
    description: Enable multi-column sorting (hold Shift to sort by multiple columns)
    default: true

steps:
  - name: Install dependencies
    tool: install
    packages: ["@tanstack/react-table", "lucide-react"]
    optional: true

  - name: Install shadcn/ui components
    tool: shell
    command: |
      if [ ! -f "components/ui/table.tsx" ]; then
        npx shadcn@latest add table --yes
      fi
      if [ ! -f "components/ui/button.tsx" ]; then
        npx shadcn@latest add button --yes
      fi

  - name: Generate TypeScript types
    tool: template
    template: templates/types.ts.jig

  - name: Generate column definitions with sorting
    tool: template
    template: templates/columns.tsx.jig

  - name: Generate sortable table component
    tool: template
    template: templates/table.tsx.jig

onSuccess: |
  Sortable data table generated successfully!

  Created files:
    - {{ dir }}/{{ name }}.tsx
    - {{ dir }}/columns.tsx
    - lib/types/{{ kebabCase(name) }}.ts

  Features:
    - Click column headers to sort
  @if(multiSort)
    - Hold Shift + click for multi-column sorting
  @end
    - Sort indicators in headers
    - Toggle between asc/desc/none

  Usage:
    import { {{ name }} } from '@/{{ dir }}/{{ name }}'
    import { columns } from '@/{{ dir }}/columns'

    <{{ name }} columns={columns} data={data} />

  Next steps:
    - Add filtering: hypergen nextjs table filterable
    - Add server features: hypergen nextjs table server
