name: changelogs
description: Add changelog documentation to your Starlight site
version: "1.0.0"

variables:
  projectFolder:
    type: string
    description: Project folder path
    default: "."

steps:
  - name: Install starlight-changelogs
    tool: shell
    command: |
      cd "{{ projectFolder }}" && bun add starlight-changelogs

onSuccess: |
  ✅ Changelog integration added!
