name: sortable
description: |
  Generate a TanStack Table with multi-column sorting support.
  Includes sort indicators, click-to-sort headers, and persistent sort state.
version: 1.0.0

variables:
  name:
    type: string
    description: Table component name in PascalCase (e.g. "UsersTable", "ProductsTable")
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  columns:
    type: array
    description: |
      Table columns in format "key:label:type:sortable" (e.g. "id:ID:string:true", "email:Email:string:true")
      Supported types: string, number, boolean, date
      Set sortable to 'true' to enable sorting on that column
    required: true

  dir:
    type: string
    description: Output directory for table component
    default: "components/tables"

  withPagination:
    type: boolean
    description: Include pagination controls
    default: true

  pageSize:
    type: number
    description: Default page size
    default: 10

  multiSort:
    type: boolean
    description: Enable multi-column sorting (hold Shift to sort by multiple columns)
    default: true

steps:
  - name: Check dependencies
    tool: shell
    command: |
      # Check if required packages are installed
      if ! bun pm ls @tanstack/react-table &>/dev/null; then
        echo "Installing required dependencies..."
        if command -v bun &> /dev/null; then
          bun add @tanstack/react-table
        elif command -v pnpm &> /dev/null; then
          pnpm add @tanstack/react-table
        elif command -v yarn &> /dev/null; then
          yarn add @tanstack/react-table
        else
          npm install @tanstack/react-table
        fi
      fi

      # Check if shadcn/ui components are installed
      if [ ! -f "components/ui/table.tsx" ]; then
        echo "Installing shadcn/ui Table component..."
        npx shadcn@latest add table --yes
      fi

      if [ ! -f "components/ui/button.tsx" ]; then
        echo "Installing shadcn/ui Button component..."
        npx shadcn@latest add button --yes
      fi

      # Install lucide-react for sort icons
      if ! bun pm ls lucide-react &>/dev/null; then
        echo "Installing lucide-react for sort icons..."
        if command -v bun &> /dev/null; then
          bun add lucide-react
        elif command -v pnpm &> /dev/null; then
          pnpm add lucide-react
        elif command -v yarn &> /dev/null; then
          yarn add lucide-react
        else
          npm install lucide-react
        fi
      fi

  - name: Create output directory
    tool: shell
    command: mkdir -p {{ dir }}

  - name: Generate TypeScript types
    tool: template
    template: templates/types.ts.jig

  - name: Generate column definitions with sorting
    tool: template
    template: templates/columns.tsx.jig

  - name: Generate sortable table component
    tool: template
    template: templates/table.tsx.jig

  - name: Instructions
    tool: shell
    command: |
      echo "✅ Sortable data table generated successfully!"
      echo ""
      echo "Created files:"
      echo "  - {{ dir }}/{{ name }}.tsx"
      echo "  - {{ dir }}/columns.tsx"
      echo "  - lib/types/{{ kebabCase(name) }}.ts"
      echo ""
      echo "Features:"
      echo "  ✓ Click column headers to sort"
@if(multiSort)
      echo "  ✓ Hold Shift + click for multi-column sorting"
@end
      echo "  ✓ Sort indicators (↑↓) in headers"
      echo "  ✓ Toggle between asc/desc/none"
      echo ""
      echo "Usage:"
      echo "  import { {{ name }} } from '@/{{ dir }}/{{ name }}'"
      echo "  import { columns } from '@/{{ dir }}/columns'"
      echo ""
      echo "  <{{ name }} columns={columns} data={data} />"
      echo ""
      echo "Next steps:"
      echo "  - Add filtering: hypergen nextjs table filterable"
      echo "  - Add server features: hypergen nextjs table server"
