name: create-page
description: |
  Generate a production-ready create page with form, validation, and Server Actions.

  Features:
  - Client Component with React Hook Form
  - Zod validation schema
  - Server Action for creation
  - Auto-redirect after success
  - Auto-detect ORM schema to generate form fields
  - shadcn/ui form components

version: 1.0.0

variables:
  name:
    type: string
    description: Resource name (singular, e.g., 'post', 'user', 'product')
    required: true
    prompt: What is the resource name? (singular, e.g., 'post', 'user')
    position: 0

  model:
    type: string
    description: Model name (PascalCase, defaults to capitalized name)
    required: false

  fields:
    type: string
    description: Comma-separated fields with types (e.g., "title:string,content:text,published:boolean")
    required: false
    prompt: |
      Enter fields (comma-separated, format: name:type)
      Leave empty to auto-detect from Prisma/Drizzle schema
      Example: title:string,content:text,published:boolean

steps:
  - name: Generate Zod validation schema
    tool: template
    template: templates/schema.ts.jig

  - name: Generate create page
    tool: template
    template: templates/create-page.tsx.jig

  - name: Generate form component
    tool: template
    template: templates/form-component.tsx.jig

  - name: Generate create Server Action
    tool: template
    template: templates/create-action.ts.jig

onSuccess: |
  Create page for '{{ name }}' generated successfully!

  Generated files:
    app/{{ name }}/new/page.tsx - Create page
    components/{{ model || name }}Form.tsx - Form component
    lib/schemas/{{ name }}-schema.ts - Zod validation
    app/actions/{{ name }}.ts - create{{ model || name }} Server Action

  Next steps:
    1. Implement the database insert in the Server Action
    2. Customize form fields and validation
    3. Visit /{{ name }}/new to test the create form
