name: rhf
description: |
  Generate a type-safe form with React Hook Form and Zod validation.
  Includes shadcn/ui Form components for beautiful, accessible forms.
version: 1.0.0

variables:
  name:
    type: string
    description: Form component name in PascalCase (e.g. "UserForm", "ProfileForm")
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  fields:
    type: array
    description: |
      Form fields in format "name:type" (e.g. "email:email", "name:text", "bio:textarea")
      Supported types: text, email, password, number, tel, url, date, time, datetime, textarea, select
    required: true

  dir:
    type: string
    description: Output directory for form component
    default: "components/forms"

  withServerAction:
    type: boolean
    description: Generate a Server Action for form submission
    default: false

  actionPath:
    type: string
    description: Path to Server Actions file (only used if withServerAction is true)
    default: "app/actions"

steps:
  - name: Install dependencies
    tool: install
    packages: [react-hook-form, zod, "@hookform/resolvers"]
    optional: true

  - name: Install shadcn/ui Form component
    tool: shell
    command: |
      if [ ! -f "components/ui/form.tsx" ]; then
        echo "Installing shadcn/ui Form component..."
        npx shadcn@latest add form --yes
      fi

  - name: Generate Zod schema
    tool: template
    template: templates/schema.ts.jig

  - name: Generate form component
    tool: template
    template: templates/form.tsx.jig

@if(withServerAction)
  - name: Generate Server Action
    tool: template
    template: templates/action.ts.jig
@end

onSuccess: |
  Form generated successfully!

  Created files:
    - {{ dir }}/{{ name }}.tsx
    - lib/schemas/{{ kebabCase(name) }}-schema.ts
  @if(withServerAction)
    - {{ actionPath }}/{{ kebabCase(name) }}-action.ts
  @end

  Usage:
    import { {{ name }} } from '@/{{ dir }}/{{ name }}'

    export default function MyPage() {
      return <{{ name }} />
    }
