name: server
description: |
  Generate a TanStack Table with server-side pagination, sorting, and filtering.
  Includes loading states, URL query params, and API integration.
version: 1.0.0

variables:
  name:
    type: string
    description: Table component name in PascalCase
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  columns:
    type: array
    description: Table columns in format "key:label:type:sortable:filterable"
    required: true

  apiEndpoint:
    type: string
    description: API endpoint for data (e.g. "/api/users")
    required: true

  dir:
    type: string
    description: Output directory
    default: "components/tables"

  pageSize:
    type: number
    description: Default page size
    default: 10

steps:
  - name: Install dependencies
    tool: install
    packages: ["@tanstack/react-table", "@tanstack/react-query"]
    optional: true

  - name: Install shadcn/ui components
    tool: shell
    command: |
      if [ ! -f "components/ui/table.tsx" ]; then
        npx shadcn@latest add table --yes
      fi
      if [ ! -f "components/ui/skeleton.tsx" ]; then
        npx shadcn@latest add skeleton --yes
      fi

  - name: Generate types
    tool: template
    template: templates/types.ts.jig

  - name: Generate API hook
    tool: template
    template: templates/use-data.ts.jig

  - name: Generate columns
    tool: template
    template: templates/columns.tsx.jig

  - name: Generate server table
    tool: template
    template: templates/table.tsx.jig

onSuccess: |
  Server-side data table generated!

  Features:
    - Server-side pagination
    - Server-side sorting
    - Server-side filtering
    - Loading states
    - URL query params

  API endpoint: {{ apiEndpoint }}

  Expected API response format:
  {
    "data": [],        // Array of rows
    "total": 100,      // Total count
    "page": 1,         // Current page
    "pageSize": 10     // Page size
  }
