name: crud
description: |
  Generate a TanStack Table with inline CRUD actions (edit, delete).
  Includes confirmation dialogs, optimistic updates, and Server Actions integration.
version: 1.0.0

variables:
  name:
    type: string
    description: Table component name in PascalCase
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  columns:
    type: array
    description: Table columns in format "key:label:type"
    required: true

  dir:
    type: string
    description: Output directory
    default: "components/tables"

  withEdit:
    type: boolean
    description: Include edit functionality
    default: true

  withDelete:
    type: boolean
    description: Include delete functionality
    default: true

  pageSize:
    type: number
    description: Default page size
    default: 10

  actionsPath:
    type: string
    description: Path to Server Actions
    default: "app/actions"

steps:
  - name: Install dependencies
    tool: install
    packages: ["@tanstack/react-table", "lucide-react"]
    optional: true

  - name: Install shadcn/ui components
    tool: shell
    command: |
      if [ ! -f "components/ui/table.tsx" ]; then
        npx shadcn@latest add table --yes
      fi
      if [ ! -f "components/ui/button.tsx" ]; then
        npx shadcn@latest add button --yes
      fi
      if [ ! -f "components/ui/dialog.tsx" ]; then
        npx shadcn@latest add dialog --yes
      fi
      if [ ! -f "components/ui/dropdown-menu.tsx" ]; then
        npx shadcn@latest add dropdown-menu --yes
      fi

  - name: Generate types
    tool: template
    template: templates/types.ts.jig

  - name: Generate Server Actions
    tool: template
    template: templates/actions.ts.jig

  - name: Generate columns with actions
    tool: template
    template: templates/columns.tsx.jig

  - name: Generate CRUD table
    tool: template
    template: templates/table.tsx.jig

@if(withDelete)
  - name: Generate delete dialog
    tool: template
    template: templates/delete-dialog.tsx.jig
@end

onSuccess: |
  CRUD data table generated!

  Features:
  @if(withEdit)
    - Edit button per row
  @end
  @if(withDelete)
    - Delete with confirmation
  @end
    - Actions dropdown menu
    - Optimistic updates

  TODO: Implement Server Actions in {{ actionsPath }}/{{ kebabCase(name) }}-actions.ts
