/**
 * The hyperdrive manifest: `spaces.yaml` on `main` of the user's one private
 * hyperdrive repository.
 *
 * The CLI keeps ONE ordinary clone of `main` at `~/.hyper/drive/` (created by
 * `hyper drive init`); every read and write happens there.
 *
 * A hyperdrive is shared by the owner's whole fleet, so several machines can
 * write it without having seen each other. git must never merge
 * `spaces.yaml`: a commit is a diff of YAML text, so a rebase picks a winner
 * and the losing entry is silently gone. Instead every write fetches, reads
 * the base manifest from `origin/main`, replays the locally recorded
 * mutations onto it BY SPACE NAME, resets onto the remote and commits — a
 * rejected push repeats that from a fresh fetch. See `applyMutation`.
 *
 * C-2 note: `services/space-git.ts` is the only git runner for SPACE branches
 * (explicit --git-dir/--work-tree). The manifest clone is an ordinary repo,
 * so this module keeps its own small `driveGit(args)` helper; the C-2 grep
 * records `manifest.ts` as the second allowed git-runner match.
 *
 * Manifest commits are generated bookkeeping, not authored history, so they
 * run with `commit.gpgsign=false` and `core.hooksPath=/dev/null`: a signer
 * or a user hook that is unavailable to (or hostile to) the CLI must not be
 * able to strand the manifest mid-write. Space commits generated by hyper
 * (`space init` and `space commit`) use the same unsigned, hook-free policy;
 * manually authored git commits still follow the user's git configuration.
 */

import { spawnSync } from "node:child_process";
import {
	closeSync,
	existsSync,
	mkdirSync,
	openSync,
	readFileSync,
	renameSync,
	rmSync,
	writeFileSync,
	writeSync,
} from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import {
	EMPTY_MANIFEST,
	isValidSpaceName,
	type Manifest,
	ManifestError,
	type SpaceEntry,
	validateManifest,
} from "#config/schema";
import { escapeControlCharacters, quoteForTerminal } from "#lib/terminal-text";
import { gitSaid, SpaceGitInterruptedError } from "#services/space-git";

const MANIFEST_FILE = "spaces.yaml";
const BRANCH = "main";

/**
 * Flags for generated manifest commits: never signed, and user hooks must
 * not run on bookkeeping commits. A pre-commit hook that rewrites or rejects
 * those would strand the manifest just as surely as a signer.
 */
const BOOKKEEPING = ["-c", "commit.gpgsign=false", "-c", "core.hooksPath=/dev/null"];

const README_TEXT = `# Hyperdrive

This is a hyperdrive repository: it holds the manifest of every hyper space
on this machine's owner's fleet.

- \`main\` (this branch) holds only this README and \`spaces.yaml\`, the manifest.
- Each space lives on its own orphan branch \`space/<name>\` or
  \`space/<group>/<name>\`, created by \`hyper space init\`.
`;

/**
 * The one place the checkout path is built: `$HYPER_HOME/drive` when
 * `HYPER_HOME` is set (tests), else `~/.hyper/drive`.
 */
export function driveCheckoutDir(): string {
	const home = process.env.HYPER_HOME;
	return home ? resolve(home, "drive") : join(homedir(), ".hyper", "drive");
}

/** The checkout's `remote.origin.url`, or null when there is no checkout. */
export function driveCheckoutOrigin(): string | null {
	const dir = driveCheckoutDir();
	if (!existsSync(join(dir, ".git"))) return null;
	const result = driveGit(["config", "--get", "remote.origin.url"], dir);
	return result.ok ? result.stdout.trim() : null;
}

function manifestPath(): string {
	return join(driveCheckoutDir(), MANIFEST_FILE);
}

interface GitResult {
	ok: boolean;
	stdout: string;
	stderr: string;
}

/**
 * Run git with an argument array — never a shell string. Prompts are disabled
 * (`GIT_TERMINAL_PROMPT=0`) so a credential question can never hang the CLI,
 * and `GIT_DIR`/`GIT_WORK_TREE` are stripped from the child env so a caller
 * inside a space's own git dir cannot redirect these commands there.
 */
function driveGit(args: readonly string[], cwd: string): GitResult {
	const env: NodeJS.ProcessEnv = { ...process.env, GIT_TERMINAL_PROMPT: "0" };
	delete env.GIT_DIR;
	delete env.GIT_WORK_TREE;
	const result = spawnSync("git", [...args], { cwd, env, encoding: "utf8" });
	if (result.signal === "SIGINT" || result.signal === "SIGTERM") {
		throw new SpaceGitInterruptedError(result.signal);
	}
	if (result.error) {
		throw new ManifestError(
			"git",
			`I couldn't run git — ${result.error.message}. Is git installed?`,
		);
	}
	return {
		ok: result.status === 0,
		stdout: result.stdout ?? "",
		stderr: result.stderr ?? "",
	};
}

function warn(message: string): void {
	process.stderr.write(`warning: ${message}\n`);
}

/** Why a push failed. These are three different problems, not one. */
export type PushFailure = "contention" | "hook-rejected" | "unreachable";

/**
 * Classify a failed push from git's own words.
 *
 * Only `! [rejected] … (fetch first)` / `non-fast-forward` is CONTENTION —
 * another machine pushed first, and retrying against a fresh fetch is the
 * right response. `! [remote rejected] … (pre-receive hook declined)` looks
 * similar but means a server-side hook refused the push, which no amount of
 * retrying will fix, and treating it as contention used to produce three
 * pointless retries followed by "the hyperdrive kept moving".
 */
export function classifyPushFailure(result: GitResult): PushFailure {
	const text = `${result.stderr ?? ""}\n${result.stdout ?? ""}`;
	if (/\[remote rejected\]/i.test(text)) return "hook-rejected";
	if (/\[rejected\]/i.test(text) && /(fetch first|non-fast-forward|stale info)/i.test(text)) {
		return "contention";
	}
	if (/non-fast-forward|fetch first|behind its remote/i.test(text)) return "contention";
	return "unreachable";
}

/**
 * Commits in the checkout need an identity. Respect the user's git config
 * when they have one; otherwise set a repo-local default so the manifest can
 * commit on a fresh machine without configuring git first.
 */
function ensureGitIdentity(dir: string): void {
	if (driveGit(["config", "user.name"], dir).stdout.trim() === "") {
		driveGit(["config", "user.name", "hyperdrive"], dir);
	}
	if (driveGit(["config", "user.email"], dir).stdout.trim() === "") {
		driveGit(["config", "user.email", "hyperdrive@localhost"], dir);
	}
}

function hasCommits(dir: string): boolean {
	return driveGit(["rev-parse", "--verify", "HEAD"], dir).ok;
}

/** True when the remote branch ref is known locally, i.e. the remote HAS a main. */
function remoteMainExists(dir: string): boolean {
	return driveGit(["rev-parse", "--verify", `origin/${BRANCH}`], dir).ok;
}

/**
 * True when the checkout holds commits the remote has not seen.
 *
 * A reachable remote that simply has no `main` yet (a failed first push, a
 * brand-new hyperdrive) counts as "ahead" whenever we have commits: those
 * commits ARE the missing `main`. Treating it as "not ahead" made every later
 * write believe there was nothing to publish, so the hyperdrive stayed
 * without a `main` forever.
 */
function isAhead(dir: string): boolean {
	if (!hasCommits(dir)) return false;
	if (!remoteMainExists(dir)) return true;
	const count = driveGit(["rev-list", "--count", `origin/${BRANCH}..HEAD`], dir);
	return count.ok && count.stdout.trim() !== "0";
}

/**
 * Push `main` on the path that does not rewrite anything: hand over a commit
 * that already exists (an init whose first push failed, or an offline write).
 * A rejected push here is NOT retried by rebasing — `applyMutation` owns the
 * replay-by-name path, and rebasing here is exactly what used to lose an
 * entry. An unreachable remote is only warned about.
 */
function pushMain(dir: string, what: string): boolean {
	const push = driveGit(["push", "origin", BRANCH], dir);
	if (push.ok) return true;
	const failure = classifyPushFailure(push);
	if (failure === "hook-rejected") throw hookRejection(dir, push, what);
	if (failure === "contention") {
		warn(
			`the hyperdrive moved while I was pushing ${what}; ` +
				"the local change is recorded and a manifest write will republish it.",
		);
		return false;
	}
	warn(
		`${what} is committed locally but I couldn't push it (the hyperdrive is unreachable) — ` +
			`the next manifest write will try again. git said: ${gitSaid(push.stderr || push.stdout)}`,
	);
	return false;
}

/** A server-side hook refused the push; retrying cannot help, so say so. */
function hookRejection(dir: string, push: GitResult, what: string): ManifestError {
	return new ManifestError(
		dir,
		`the hyperdrive server refused ${what}. This is not a conflict — a hook on the remote declined ` +
			`it, so retrying will not help. git said: ${gitSaid(push.stderr || push.stdout)}`,
	);
}

/**
 * Write the README and the empty manifest, commit them, and push with an
 * upstream. Split out from `ensureDriveCheckout` because it must also be able
 * to resume a checkout whose first commit never happened (a signer failure, a
 * crash, a remote that was briefly unreachable) — leaving a `.git` alone is
 * not evidence that a checkout is finished.
 */
function initialiseMain(dir: string, remote: string): void {
	ensureGitIdentity(dir);
	writeFileSync(join(dir, "README.md"), README_TEXT, "utf-8");
	writeFileSync(
		join(dir, MANIFEST_FILE),
		serializeManifest(structuredClone(EMPTY_MANIFEST)),
		"utf-8",
	);
	driveGit(["add", "README.md", MANIFEST_FILE], dir);
	const commit = driveGit([...BOOKKEEPING, "commit", "-m", "manifest: initialise hyperdrive"], dir);
	if (!commit.ok) {
		throw new ManifestError(dir, `the initial commit failed: ${gitSaid(commit.stderr)}`);
	}
	const push = driveGit(["push", "-u", "origin", BRANCH], dir);
	if (!push.ok) {
		const failure = classifyPushFailure(push);
		if (failure === "hook-rejected") throw hookRejection(dir, push, "the initial push");
		warn(
			`the hyperdrive is initialised locally but I couldn't push it to ${escapeControlCharacters(remote)} — ` +
				`the next manifest write will try again. git said: ${gitSaid(push.stderr || push.stdout)}`,
		);
	}
}

/**
 * Ensure the local clone of the hyperdrive's `main` branch exists.
 *
 * - Already cloned: verify the origin matches `remote` (a mismatch means the
 *   checkout belongs to a different hyperdrive), finish an unfinished init if
 *   the branch has no commit yet, then fast-forward and push anything local.
 * - No clone: probe the remote with `git ls-remote`. When the remote has a
 *   `main`, clone it; when it is reachable but empty, initialise `main` and
 *   push. An unreachable remote is a friendly error naming the URL.
 *
 * `created` is true when this call produced the checkout (clone or init).
 */
export function ensureDriveCheckout(remote: string): { dir: string; created: boolean } {
	const dir = driveCheckoutDir();

	if (existsSync(join(dir, ".git"))) {
		const origin = driveGit(["config", "--get", "remote.origin.url"], dir).stdout.trim();
		if (origin !== remote) {
			throw new ManifestError(
				dir,
				`the hyperdrive checkout there is a clone of ${quoteForTerminal(origin)}, ` +
					`but your config points at ${quoteForTerminal(remote)}. ` +
					"Move the checkout away or fix `remote` in your drive.toml.",
			);
		}
		// A `.git` on its own is not a finished checkout: a failed first commit
		// leaves an unborn branch with the files staged, and reporting "already
		// exists" there would leave the hyperdrive without a `main` forever.
		if (!hasCommits(dir)) {
			initialiseMain(dir, remote);
			return { dir, created: true };
		}
		const pull = driveGit(["pull", "--ff-only", "origin", BRANCH], dir);
		if (!pull.ok) {
			// Not "(offline?)": a fast-forward that cannot happen is usually
			// LOCAL divergence, and naming it offline sends the reader after the
			// wrong problem. A manifest write reconciles properly regardless.
			warn(
				`I couldn't fast-forward the hyperdrive checkout from ${escapeControlCharacters(remote)} — continuing with the ` +
					`local copy. This is usually local divergence or an unreachable remote, not a lost ` +
					`entry: the next manifest write reconciles by space name. git said: ` +
					`${gitSaid(pull.stderr || pull.stdout)}`,
			);
		}
		// Publish anything local that the remote has not seen. A non-empty
		// pending log is NOT safe to clear after a plain push of HEAD: a crash
		// between recording and committing leaves the log holding entries HEAD
		// has never contained, and clearing there would lose them. Reconcile
		// (replay onto the fetched base and push) instead — and do it under
		// the manifest lock, because this path and `applyMutation` must not
		// interleave.
		if (isAhead(dir) || loadPending(dir).length > 0) {
			withManifestLock(dir, "reconcile the pending manifest changes", () => {
				applyMutation(dir);
			});
		}
		return { dir, created: false };
	}

	const probe = driveGit(["ls-remote", "--heads", remote, BRANCH], process.cwd());
	if (!probe.ok) {
		throw new ManifestError(
			remote,
			`I couldn't reach your hyperdrive at ${escapeControlCharacters(remote)} — check the URL and your network. ` +
				`git said: ${gitSaid(probe.stderr || probe.stdout) || "no output"}`,
		);
	}

	mkdirSync(dir, { recursive: true });

	if (probe.stdout.includes(`refs/heads/${BRANCH}`)) {
		const clone = driveGit(
			["clone", "--branch", BRANCH, "--single-branch", remote, dir],
			process.cwd(),
		);
		if (!clone.ok) {
			throw new ManifestError(
				remote,
				`cloning your hyperdrive failed: ${gitSaid(clone.stderr || clone.stdout)}`,
			);
		}
		ensureGitIdentity(dir);
		return { dir, created: true };
	}

	// Reachable but no `main` yet: this is a brand-new hyperdrive.
	for (const step of [
		["init", "-b", BRANCH],
		["remote", "add", "origin", remote],
	] as const) {
		const result = driveGit(step, dir);
		if (!result.ok) {
			throw new ManifestError(dir, `git ${step[0]} failed: ${gitSaid(result.stderr)}`);
		}
	}
	initialiseMain(dir, remote);
	return { dir, created: true };
}

/**
 * Serialise a manifest with a stable key order and spaces sorted by `name`,
 * so rewrites are diff-minimal and "did anything change?" is a string
 * comparison. Sorting compares code points, not the ambient locale, so the
 * file reads the same on every machine.
 */
function serializeManifest(manifest: Manifest): string {
	const spaces = [...manifest.spaces]
		.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
		.map((space) => ({
			name: space.name,
			branch: space.branch,
			group: space.group,
			path: space.path,
			layout: space.layout,
			repos: space.repos.map((repo) =>
				repo.slug === undefined
					? { url: repo.url, default_branch: repo.default_branch }
					: { url: repo.url, default_branch: repo.default_branch, slug: repo.slug },
			),
			cadence: space.cadence,
			tracked: space.tracked,
			public: space.public,
		}));
	return stringifyYaml({ spaces });
}

/**
 * Read and validate `spaces.yaml` from the checkout. A missing checkout is a
 * friendly error pointing at `hyper drive init`; a missing file on an
 * initialised checkout reads as an empty manifest.
 */
export function readManifest(): Manifest {
	const dir = driveCheckoutDir();
	if (!existsSync(join(dir, ".git"))) {
		throw new ManifestError(
			dir,
			"there's no hyperdrive checkout there yet — run `hyper drive init` first.",
		);
	}
	const path = manifestPath();
	if (!existsSync(path)) return structuredClone(EMPTY_MANIFEST);
	let raw: unknown;
	try {
		raw = parseYaml(readFileSync(path, "utf-8"));
	} catch (err) {
		const detail = err instanceof Error ? err.message : String(err);
		throw new ManifestError(path, `the YAML didn't parse — ${escapeControlCharacters(detail)}`);
	}
	return validateManifest(path, raw);
}

/* ------------------------------------------------------------------------- */
/* Serialisation between processes                                          */
/* ------------------------------------------------------------------------- */

const LOCK_FILE = "hyper-manifest.lock";
const LOCK_ATTEMPTS = 50;
const LOCK_RETRY_MS = 100;

/** Is a pid still running? EPERM means it exists but belongs to someone else. */
function isProcessAlive(pid: number): boolean {
	try {
		process.kill(pid, 0);
		return true;
	} catch (err) {
		return (err as NodeJS.ErrnoException).code === "EPERM";
	}
}

function sleepSync(ms: number): void {
	Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

function lockPath(dir: string): string {
	return join(dir, ".git", LOCK_FILE);
}

/** The pid recorded in a lock file, or null when it holds none. */
function lockOwner(path: string): number | null {
	try {
		const pid = Number.parseInt(readFileSync(path, "utf-8").trim(), 10);
		return Number.isInteger(pid) && pid > 0 ? pid : null;
	} catch {
		return null;
	}
}

/**
 * Hold an exclusive lock on the manifest for the duration of `fn`.
 *
 * Two processes writing the same checkout — a SessionEnd hook and a parallel
 * agent are the realistic case — used to interleave read/replay/write/push
 * and silently drop each other's entries while both reported success. The
 * lock file carries the owning pid so a process killed mid-write does not
 * wedge the checkout forever: a lock whose owner is gone is reclaimed.
 */
function withManifestLock<T>(dir: string, what: string, fn: () => T): T {
	const path = lockPath(dir);
	mkdirSync(join(dir, ".git"), { recursive: true });
	for (let attempt = 0; attempt < LOCK_ATTEMPTS; attempt++) {
		try {
			const fd = openSync(path, "wx");
			try {
				writeSync(fd, `${process.pid}\n`);
			} finally {
				closeSync(fd);
			}
			try {
				return fn();
			} finally {
				rmSync(path, { force: true });
			}
		} catch (err) {
			if ((err as NodeJS.ErrnoException).code !== "EEXIST") throw err;
			const owner = lockOwner(path);
			if (owner !== null && !isProcessAlive(owner)) {
				// The owner died holding it: reclaim rather than wait forever.
				rmSync(path, { force: true });
				continue;
			}
			sleepSync(LOCK_RETRY_MS);
		}
	}
	throw new ManifestError(
		dir,
		`another hyperdrive write has held ${path} for too long, so I stopped rather than ` +
			`${what} over it. If no process is still running, delete that file and try again.`,
	);
}

/** One intended change, recorded until it has been pushed. */
type Mutation = { name: string; entry?: SpaceEntry; verb?: "add" | "update" | "remove" };
// `entry` set: upsert this space under that name. `entry` absent: remove it.
// `verb` is bookkeeping for the commit message, derived at replay time.

/**
 * Local mutations waiting to reach the remote, one JSON object per line.
 *
 * This file is the record of intent that survives a failed push. Replaying
 * commits instead was the other option, but a commit is a diff of YAML TEXT:
 * rebasing two machines' edits to `spaces.yaml` is git merging the file, and
 * whichever entry lost that merge was silently dropped from the manifest.
 * Mutations are keyed by space NAME, so replaying them onto whatever the
 * remote currently holds cannot lose an entry.
 */
const PENDING_FILE = ".hyper-pending.jsonl";

const MAX_PUSH_ATTEMPTS = 3;

function pendingPath(dir: string): string {
	return join(dir, PENDING_FILE);
}

/** Keep the pending log out of `git status`; it is local bookkeeping. */
function excludePendingFile(dir: string): void {
	const exclude = join(dir, ".git", "info", "exclude");
	try {
		mkdirSync(join(dir, ".git", "info"), { recursive: true });
		const current = existsSync(exclude) ? readFileSync(exclude, "utf-8") : "";
		if (!current.split("\n").includes(PENDING_FILE)) {
			writeFileSync(
				exclude,
				`${current}${current && !current.endsWith("\n") ? "\n" : ""}${PENDING_FILE}\n`,
			);
		}
	} catch {
		// Not being able to hide the file is cosmetic: we only ever `git add`
		// spaces.yaml, so the pending log can never reach the remote.
	}
}

function isMutation(value: unknown): value is Mutation {
	if (typeof value !== "object" || value === null) return false;
	const mutation = value as Record<string, unknown>;
	if (typeof mutation.name !== "string" || mutation.name === "") return false;
	if (mutation.entry === undefined) return true;
	return typeof mutation.entry === "object" && mutation.entry !== null;
}

function loadPending(dir: string): Mutation[] {
	const path = pendingPath(dir);
	if (!existsSync(path)) return [];
	return readFileSync(path, "utf-8")
		.split("\n")
		.filter((line) => line.trim() !== "")
		.flatMap((line) => {
			try {
				const parsed = JSON.parse(line) as unknown;
				if (isMutation(parsed)) return [parsed];
				warn(`dropping a malformed line from ${path}: ${escapeControlCharacters(line.trim())}`);
				return [];
			} catch {
				// A truncated last line from a killed process must not wedge
				// every later write; drop it, loudly.
				warn(`dropping an unreadable line from ${path}: ${escapeControlCharacters(line.trim())}`);
				return [];
			}
		});
}

function savePending(dir: string, pending: Mutation[]): void {
	const path = pendingPath(dir);
	if (pending.length === 0) {
		rmSync(path, { force: true });
		return;
	}
	// Temp + rename so a reader never sees a half-written log.
	const tmp = `${path}.tmp-${process.pid}`;
	writeFileSync(tmp, `${pending.map((mutation) => JSON.stringify(mutation)).join("\n")}\n`);
	rmSync(path, { force: true });
	renameSync(tmp, path);
}

function clearPendingLog(dir: string): void {
	rmSync(pendingPath(dir), { force: true });
}

/** Apply recorded mutations to a base manifest, keyed by space name. */
function replay(base: SpaceEntry[], mutations: readonly Mutation[]): SpaceEntry[] {
	const byName = new Map(base.map((space) => [space.name, space]));
	for (const mutation of mutations) {
		if (mutation.entry === undefined) byName.delete(mutation.name);
		else byName.set(mutation.name, mutation.entry);
	}
	return [...byName.values()];
}

/** The manifest as it exists at a given ref, empty when that ref has none. */
function readManifestAt(dir: string, ref: string): SpaceEntry[] {
	const show = driveGit(["show", `${ref}:${MANIFEST_FILE}`], dir);
	if (!show.ok) return [];
	let raw: unknown;
	try {
		raw = parseYaml(show.stdout);
	} catch (err) {
		const detail = err instanceof Error ? err.message : String(err);
		throw new ManifestError(
			`${ref}:${MANIFEST_FILE}`,
			`the YAML didn't parse — ${escapeControlCharacters(detail)}`,
		);
	}
	if (raw === null || raw === undefined) return [];
	return validateManifest(`${ref}:${MANIFEST_FILE}`, raw).spaces;
}

/**
 * Finish or undo whatever git left half-done. A rebase or a detached HEAD
 * from an interrupted run would otherwise poison every later write, and
 * calling that "(offline?)" sends the reader looking at the wrong problem.
 */
function recoverCheckout(dir: string): void {
	const gitDir = join(dir, ".git");
	const inRebase =
		existsSync(join(gitDir, "rebase-merge")) || existsSync(join(gitDir, "rebase-apply"));
	if (inRebase) {
		const abort = driveGit(["rebase", "--abort"], dir);
		if (abort.ok) {
			warn("an interrupted rebase was rolled back before writing the manifest.");
		} else {
			// A crash mid-rebase can leave an INCOMPLETE state dir that `git
			// rebase --abort` refuses to read. That state is bookkeeping only,
			// and rolling it back is exactly what abort would have done; the
			// write below resets to the remote anyway, so remove it rather than
			// wedge every later manifest command.
			rmSync(join(gitDir, "rebase-merge"), { recursive: true, force: true });
			rmSync(join(gitDir, "rebase-apply"), { recursive: true, force: true });
			warn(
				`git couldn't roll back an interrupted rebase (${gitSaid(abort.stderr)}), so I removed the ` +
					"state git left behind and continued from the remote.",
			);
		}
	}
	const head = driveGit(["symbolic-ref", "-q", "HEAD"], dir);
	if (!head.ok) {
		const checkout = driveGit(["checkout", BRANCH], dir);
		if (!checkout.ok) {
			throw new ManifestError(
				dir,
				`the checkout is on a detached HEAD and I couldn't get back to ${BRANCH}: ${gitSaid(checkout.stderr)}`,
			);
		}
	}
}

/**
 * Record one mutation and get it onto the remote. LOCKED: callers hold the
 * manifest lock (see `withManifestLock`); `ensureDriveCheckout` reconciles
 * through here so its push path is serialised too.
 *
 * With no new mutation this is a pure reconcile: it publishes what the
 * pending log already records. `ensureDriveCheckout` uses that to recover
 * from a crash between recording and committing, instead of clearing the
 * log on a push whose HEAD had never contained those entries.
 *
 * The sequence deliberately never lets git merge `spaces.yaml`: it fetches,
 * reads the BASE manifest from `origin/main` (or from local HEAD when the
 * remote has no `main` or is unreachable), replays every recorded mutation
 * onto that base by name, and either commits and pushes, or just pushes when
 * the remote lacks a `main` yet. A rejected push repeats from a fresh fetch,
 * at most {@link MAX_PUSH_ATTEMPTS} times.
 *
 * A reachable remote with NO `main` is not "offline": it is a first push
 * that has not landed, and this write publishes it with `push -u` instead of
 * waiting for a future change to carry it. git's words for the push are
 * classified — contention retries, a server hook declines with an error,
 * and only a genuinely unreachable remote warns and keeps things local.
 *
 * Each replayed mutation gets its OWN commit, so the remote's history shows
 * what actually happened (`manifest: add offB`, `manifest: update research`)
 * instead of one commit labelled with whichever write happened to carry it.
 * The verb is decided against the base being replayed onto, so an offline
 * machine's "add" becomes an "update" in history when the space already
 * exists remotely. A mutation that changes nothing is skipped entirely — no
 * commit, no line in the pending log.
 *
 * **Last writer wins, by name.** Replaying a pending mutation re-asserts that
 * space's entry even if another machine has since removed it: a machine that
 * was offline while a space was deleted elsewhere will resurrect it when it
 * comes back. That is a deliberate trade — refusing to replay would silently
 * drop the offline machine's own entries, which is the failure this whole
 * design exists to prevent — and it resolves on the next write from the
 * machine that actually removed the space.
 */
/**
 * Refuse an upsert whose name is already on a DIFFERENT branch, judged against
 * the manifest base being replayed onto.
 *
 * The manifest is keyed by name, so a name can only ever mean one space. The
 * command checks this before it starts writing, but that check reads a
 * checkout that another machine may have written to since — so the decision is
 * made again here, on the freshly-fetched base, inside the lock. A same-branch
 * entry is an update and passes.
 */
export class SpaceNameConflictError extends ManifestError {
	constructor(
		name: string,
		branch: string,
		readonly existingBranch: string,
	) {
		super(
			join(driveCheckoutDir(), MANIFEST_FILE),
			`the space called ${quoteForTerminal(name)} is on branch ${escapeControlCharacters(existingBranch)} on the ` +
				`hyperdrive, and this run would put ${escapeControlCharacters(branch)} in its place. Space names are unique ` +
				`across groups, so two spaces cannot share one name — pass a name of its own.`,
		);
		this.name = "SpaceNameConflictError";
	}
}

function assertNameFreeOnBase(base: readonly SpaceEntry[], entry: SpaceEntry | undefined): void {
	if (entry === undefined) return;
	const existing = base.find((space) => space.name === entry.name);
	if (existing === undefined || existing.branch === entry.branch) return;
	throw new SpaceNameConflictError(entry.name, entry.branch, existing.branch);
}

function applyMutation(dir: string, mutation?: Mutation): void {
	recoverCheckout(dir);
	excludePendingFile(dir);

	// Held in memory and only written to disk just before a commit: a
	// no-op must not leave a junk line behind for the next run to replay.
	const pending = mutation === undefined ? loadPending(dir) : [...loadPending(dir), mutation];
	if (mutation === undefined && pending.length === 0) {
		// Nothing recorded; but HEAD may still be ahead of a remote that has
		// never seen a main — a first push is a publish, not a reconcile.
		if (isAhead(dir)) {
			if (pushMain(dir, "the pending hyperdrive init")) clearPendingLog(dir);
		}
		return;
	}

	for (let attempt = 1; attempt <= MAX_PUSH_ATTEMPTS; attempt++) {
		const fetched = driveGit(["fetch", "origin", BRANCH], dir);

		if (!fetched.ok) {
			// `git fetch origin main` exits 128 ("couldn't find remote ref
			// main") BOTH when the remote is unreachable AND when it is
			// reachable but simply has no `main` yet — the exit code alone
			// cannot tell those apart, and guessing "offline" here stranded
			// machines whose first push had been refused. Probe with ls-remote
			// before believing the network is down.
			const probe = driveGit(["ls-remote", "--heads", "origin", BRANCH], dir);
			if (probe.ok && probe.stdout.trim() === "") {
				// Reachable, empty: publish our history as the remote's first
				// `main` rather than waiting for some future change to carry it.
				commitReplay(dir, readManifestAt(dir, "HEAD"), pending);
				const push = driveGit(["push", "-u", "origin", BRANCH], dir);
				if (push.ok) {
					clearPendingLog(dir);
					return;
				}
				const failure = classifyPushFailure(push);
				if (failure === "hook-rejected") {
					throw hookRejection(dir, push, `the first push of ${BRANCH}`);
				}
				warn(
					`the hyperdrive has no ${BRANCH} yet and I couldn't create it; the local copy is kept — ` +
						`git said: ${gitSaid(push.stderr || push.stdout)}`,
				);
				return;
			}
			// No remote to reconcile with: keep the entries locally, stacked on
			// HEAD, and let the next run publish them.
			const base = readManifestAt(dir, "HEAD");
			if (commitReplay(dir, base, pending)) {
				warn(
					`the hyperdrive is unreachable, so ${escapeControlCharacters(mutation?.name ?? "the recorded changes")} is recorded ` +
						"locally only — the next write will publish it.",
				);
				return;
			}
			warn(`the hyperdrive is unreachable and everything is already recorded — nothing to commit.`);
			return;
		}

		// The remote answered but has no `main` ref yet (or a first push that
		// never landed): local HEAD is the only history, and publishing it is
		// a push, not a reconcile.
		if (!remoteMainExists(dir)) {
			const push = driveGit(["push", "-u", "origin", BRANCH], dir);
			if (push.ok) {
				clearPendingLog(dir);
				return;
			}
			const failure = classifyPushFailure(push);
			if (failure === "hook-rejected") throw hookRejection(dir, push, "the first push");
			warn(
				`the hyperdrive answered but couldn't take ${BRANCH}; the local copy is kept — ` +
					`git said: ${gitSaid(push.stderr || push.stdout)}`,
			);
			return;
		}

		const base = readManifestAt(dir, `origin/${BRANCH}`);
		// Name uniqueness is re-checked HERE, under the lock, against the base
		// just read from the remote — not against whatever the command saw in a
		// checkout that may be minutes stale. Two machines can legitimately both
		// pass a pre-check (each read a manifest without the other's space), and
		// then `replay()` replaces by name with no branch comparison: `x` as
		// `space/x` and `x` as `space/g/x` would silently become one entry. The
		// same branch still replaces — that is the update path.
		assertNameFreeOnBase(base, mutation?.entry);
		const reset = driveGit(["reset", "--hard", `origin/${BRANCH}`], dir);
		if (!reset.ok) {
			throw new ManifestError(
				dir,
				`I couldn't reset the checkout onto the remote ${BRANCH}: ${gitSaid(reset.stderr)}`,
			);
		}

		if (!commitReplay(dir, base, pending)) {
			// The remote already says exactly this: nothing to commit, nothing pending.
			clearPendingLog(dir);
			return;
		}

		const push = driveGit(["push", "origin", BRANCH], dir);
		if (push.ok) {
			clearPendingLog(dir);
			return;
		}
		const failure = classifyPushFailure(push);
		if (failure === "hook-rejected") {
			throw hookRejection(dir, push, mutation?.name ?? "the recorded changes");
		}
		if (failure === "contention") {
			warn(
				`the hyperdrive moved while I was pushing ${mutation?.name ?? "the recorded changes"}; ` +
					`retrying against the current remote (attempt ${attempt} of ${MAX_PUSH_ATTEMPTS}).`,
			);
			continue;
		}
		warn(
			`${mutation?.name ?? "the recorded changes"} is recorded locally but I couldn't push it ` +
				"(the hyperdrive is unreachable) — the next manifest write will try again.",
		);
		return;
	}

	warn(
		`I couldn't publish ${mutation?.name ?? "the recorded changes"} after ${MAX_PUSH_ATTEMPTS} attempts ` +
			"because the hyperdrive kept moving. The change is recorded locally and no entry was lost; " +
			"run any manifest command again to retry.",
	);
}

/**
 * Apply the pending mutations to a base manifest, committing one change at a
 * time so each keeps its own message. Returns false when nothing changed, in
 * which case nothing is written and nothing is recorded.
 *
 * The steps are computed before anything is touched, so a no-op leaves no
 * trace, and the pending log is written BEFORE the first commit: a crash
 * between the commit and its push must never leave a change committed with
 * nothing left to replay it. The verb in each message is derived from the
 * base at that step (add when the name is new there, update when it already
 * exists).
 */
function commitReplay(dir: string, base: SpaceEntry[], pending: readonly Mutation[]): boolean {
	const steps: Array<{ mutation: Mutation; content: string }> = [];
	let spaces = base;
	let previous = serializeManifest({ spaces });
	for (const mutation of pending) {
		const existed = spaces.some((space) => space.name === mutation.name);
		spaces = replay(spaces, [mutation]);
		const content = serializeManifest({ spaces });
		if (content === previous) continue;
		previous = content;
		steps.push({
			mutation: {
				...mutation,
				verb: mutation.entry === undefined ? "remove" : existed ? "update" : "add",
			} as Mutation,
			content,
		});
	}
	if (steps.length === 0) return false;

	savePending(dir, [...pending]);
	for (const step of steps) {
		writeSpacesYaml(dir, step.content);
		commitManifest(dir, step.mutation);
	}
	return true;
}

function writeSpacesYaml(dir: string, content: string): void {
	writeFileSync(manifestPath(), content, "utf-8");
	driveGit(["add", MANIFEST_FILE], dir);
}

function commitManifest(dir: string, mutation: Mutation): void {
	const verb = mutation.verb ?? (mutation.entry === undefined ? "remove" : "update");
	const commit = driveGit(
		[...BOOKKEEPING, "commit", "-m", `manifest: ${verb} ${mutation.name}`],
		dir,
	);
	if (!commit.ok) {
		// git explains "nothing to commit" on STDOUT, so stderr alone can leave
		// an empty reason.
		const reason = commit.stderr.trim() || commit.stdout.trim();
		throw new ManifestError(dir, `committing the manifest failed: ${reason}`);
	}
}

/**
 * Reject a space whose name or branch could escape the manifest's world:
 * `space/../../etc` or `-rf` as a name/branch would be dangerous as a path
 * segment or ref. The name shape is re-checked here because an upserted entry
 * need never have been read back, and the branch is checked by git itself,
 * the same way T-5 will create it.
 */
function validateSpaceName(entry: SpaceEntry): void {
	if (!isValidSpaceName(entry.name)) {
		throw new ManifestError(
			join(driveCheckoutDir(), MANIFEST_FILE),
			`\`${entry.name}\` is not a valid space name: it must be lowercase letters, digits, dots, ` +
				`underscores and dashes, no "..". Names double as path segments and half a branch name, so ` +
				"they have to be boring by construction.",
		);
	}
	const dir = driveCheckoutDir();
	if (existsSync(join(dir, ".git"))) {
		const check = driveGit(["check-ref-format", "--branch", entry.branch], dir);
		if (!check.ok) {
			throw new ManifestError(
				join(dir, MANIFEST_FILE),
				`${quoteForTerminal(entry.branch)} is not a valid branch name for space ${quoteForTerminal(entry.name)} ` +
					`(git said: ${gitSaid(check.stderr || check.stdout)}).`,
			);
		}
	}
}

/**
 * Add a space to the manifest, or replace the entry of the same name. The
 * write is replayed by name onto the remote, so two machines adding spaces at
 * the same time both keep theirs.
 */
/**
 * Add a space to the manifest, or replace the entry of the same name. Runs
 * under the manifest lock so a parallel agent or hook cannot interleave its
 * write with this one — that is exactly how two processes used to drop each
 * other's entries while both reported success.
 */
export function upsertSpace(entry: SpaceEntry): void {
	const dir = driveCheckoutDir();
	withManifestLock(dir, `upsert ${entry.name}`, () => {
		validateSpaceName(entry);
		applyMutation(dir, { name: entry.name, entry });
	});
}

/** Remove a space from the manifest. */
export function removeSpace(name: string): void {
	const dir = driveCheckoutDir();
	withManifestLock(dir, `remove ${name}`, () => {
		applyMutation(dir, { name });
	});
}
