name: add
description: |
  Add a loading UI to a Next.js App Router route segment.
  Creates loading.tsx that shows while the page is loading via React Suspense.
version: 1.0.0

variables:
  path:
    type: string
    description: Route segment path relative to app/ (e.g. "dashboard", "blog/[slug]")
    required: true

  style:
    type: enum
    description: Loading UI style
    values: [skeleton, spinner, pulse]
    default: skeleton

steps:
  - name: Generate loading UI
    tool: template
    template: templates/loading.tsx.jig
