name: rhf
description: |
  Generate a type-safe form with React Hook Form and Zod validation.
  Includes shadcn/ui Form components for beautiful, accessible forms.
version: 1.0.0

variables:
  name:
    type: string
    description: Form component name in PascalCase (e.g. "UserForm", "ProfileForm")
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  fields:
    type: array
    description: |
      Form fields in format "name:type" (e.g. "email:email", "name:text", "bio:textarea")
      Supported types: text, email, password, number, tel, url, date, time, datetime, textarea, select
    required: true

  dir:
    type: string
    description: Output directory for form component
    default: "components/forms"

  withServerAction:
    type: boolean
    description: Generate a Server Action for form submission
    default: false

  actionPath:
    type: string
    description: Path to Server Actions file (only used if withServerAction is true)
    default: "app/actions"

steps:
  - name: Check dependencies
    tool: shell
    command: |
      # Check if required packages are installed
      if ! bun pm ls react-hook-form &>/dev/null; then
        echo "Installing required dependencies..."
        if command -v bun &> /dev/null; then
          bun add react-hook-form zod @hookform/resolvers
        elif command -v pnpm &> /dev/null; then
          pnpm add react-hook-form zod @hookform/resolvers
        elif command -v yarn &> /dev/null; then
          yarn add react-hook-form zod @hookform/resolvers
        else
          npm install react-hook-form zod @hookform/resolvers
        fi
      fi

      # Check if shadcn/ui Form component is installed
      if [ ! -f "components/ui/form.tsx" ]; then
        echo "Installing shadcn/ui Form component..."
        npx shadcn@latest add form --yes
      fi

  - name: Create output directory
    tool: shell
    command: mkdir -p {{ dir }}

  - name: Generate Zod schema
    tool: template
    template: templates/schema.ts.jig

  - name: Generate form component
    tool: template
    template: templates/form.tsx.jig

@if(withServerAction)
  - name: Create actions directory
    tool: shell
    command: mkdir -p {{ actionPath }}

  - name: Generate Server Action
    tool: template
    template: templates/action.ts.jig
@end

  - name: Instructions
    tool: shell
    command: |
      echo "✅ Form generated successfully!"
      echo ""
      echo "Created files:"
      echo "  - {{ dir }}/{{ name }}.tsx"
      echo "  - lib/schemas/{{ kebabCase(name) }}-schema.ts"
@if(withServerAction)
      echo "  - {{ actionPath }}/{{ kebabCase(name) }}-action.ts"
@end
      echo ""
      echo "Usage:"
      echo "  import { {{ name }} } from '@/{{ dir }}/{{ name }}'"
      echo ""
      echo "  export default function MyPage() {"
      echo "    return <{{ name }} />"
      echo "  }"
