name: enum
description: |
  Generate a DDD-style enum (const object pattern) with TypeScript type,
  Zod schema, type guard, label helper, and iteration utilities.

  Uses the const object pattern instead of TypeScript enums for better
  tree-shaking, type inference, and runtime utilities.

  Time saved: 10-20 min → 1 min

version: 1.0.0

variables:
  name:
    type: string
    description: Enum name (PascalCase — e.g., 'UserRole', 'TodoStatus', 'OrderState')
    required: true
    position: 0
    prompt: What is the enum name? (PascalCase, e.g., 'UserRole', 'TodoStatus')

  values:
    type: string
    description: Comma-separated enum values (e.g., "admin,member,viewer")
    required: false
    prompt: |
      Enter enum values (comma-separated)
      Leave empty for AI to infer from name
      Example: admin,member,viewer

onSuccess: |
  Enum '{{ name }}' generated successfully!

  Generated files:
    lib/domain/enums/{{ name }}.ts

  Usage:
    import { {{ name }}, type {{ name }}Type, is{{ name }} } from '@/lib/domain/enums/{{ name }}'
    const role = {{ name }}.ADMIN
    is{{ name }}('admin') // true

steps:
  - name: Generate enum module
    tool: template
    template: templates/enum.ts.jig
