name: add
description: |
  Add a new page to a Next.js App Router project.
  Creates page.tsx in the appropriate route segment directory.
  Optionally generates loading.tsx, error.tsx, and a route-specific layout.
version: 1.0.0

variables:
  pagePath:
    type: string
    description: |
      Route path relative to app/ (e.g. "about", "blog/[slug]", "dashboard/settings").
      Supports dynamic segments [param], catch-all [...slug], and optional catch-all [[...slug]].
    required: true
    position: 0

  pageDescription:
    type: string
    description: Brief description of what this page does
    suggestion: ""

  withLayout:
    type: boolean
    description: Also generate a layout.tsx for this route segment
    default: false

  withLoading:
    type: boolean
    description: Also generate a loading.tsx for this route segment
    default: false

  withError:
    type: boolean
    description: Also generate an error.tsx boundary for this route segment
    default: false

steps:
  - name: Generate page scaffold
    tool: template
    template: templates/page.tsx.jig

  - name: Generate layout
    tool: recipe
    recipe: ../../layout/add/recipe.yml
    when: "withLayout === true"
    args:
      path: "{{ pagePath }}"
      layoutDescription: "Layout for {{ pageDescription }}"

  - name: Generate loading UI
    tool: recipe
    recipe: ../../loading/add/recipe.yml
    when: "withLoading === true"
    args:
      path: "{{ pagePath }}"

  - name: Generate error boundary
    tool: recipe
    recipe: ../../error/add/recipe.yml
    when: "withError === true"
    args:
      path: "{{ pagePath }}"
