name: create
description: Create the Next.js project file structure with Tailwind CSS and TypeScript
version: 1.0.0

variables:
  name:
    type: string
    required: true
  description:
    type: string
    default: "A Next.js application"
  useSrcDir:
    type: boolean
    default: false
  linter:
    type: enum
    values: [eslint, biome, none]
    default: eslint

steps:
  - name: Generate project files
    sequence:
      - name: Generate package.json
        template: templates/package.json.jig

      - name: Generate tsconfig.json
        template: templates/tsconfig.json.jig

      - name: Generate next.config.ts
        template: templates/next.config.ts.jig

      - name: Generate postcss.config.mjs
        template: templates/postcss.config.mjs.jig

      - name: Generate next-env.d.ts
        template: templates/next-env.d.ts.jig

      - name: Generate .gitignore
        template: templates/gitignore.jig

      - name: Generate .env.example
        template: templates/env.example.jig

      - name: Generate README.md
        template: templates/README.md.jig

      - name: Generate ESLint config
        template: templates/eslint.config.mjs.jig
        when: "linter === 'eslint'"

      - name: Generate Biome config
        template: templates/biome.json.jig
        when: "linter === 'biome'"

  - name: Generate app files
    sequence:
      - name: Generate globals.css
        template: templates/app/globals.css.jig

      - name: Generate layout.tsx
        template: templates/app/layout.tsx.jig

      - name: Generate page.tsx
        template: templates/app/page.tsx.jig

  - name: Copy static assets
    sequence:
      - name: Copy Next.js logo
        template: templates/public/next.svg.jig

      - name: Copy Vercel logo
        template: templates/public/vercel.svg.jig

      - name: Copy file icon
        template: templates/public/file.svg.jig

      - name: Copy globe icon
        template: templates/public/globe.svg.jig

      - name: Copy window icon
        template: templates/public/window.svg.jig
