name: graphql
description: |
  Generate a basic GraphQL endpoint using GraphQL Yoga.
  Provides a foundation for GraphQL APIs with schema-first development.
version: 1.0.0

variables:
  dir:
    type: string
    description: Output directory for GraphQL endpoint
    default: "app/api/graphql"

  playground:
    type: boolean
    description: Enable GraphQL Playground in development
    default: true

  auth:
    type: boolean
    description: Add authentication context
    default: false

steps:
  - name: Check GraphQL dependencies
    tool: shell
    command: |
      if ! grep -q "graphql-yoga" package.json; then
        echo "⚠️  GraphQL Yoga not found. Installing dependencies..."
        npm install graphql graphql-yoga
      fi

  - name: Create GraphQL directory
    tool: shell
    command: mkdir -p {{ dir }}

  - name: Create schema directory
    tool: shell
    command: mkdir -p lib/graphql

  - name: Generate GraphQL route handler
    tool: template
    template: templates/route.ts.jig

  - name: Generate GraphQL schema
    tool: template
    template: templates/schema.ts.jig

  - name: Generate GraphQL resolvers
    tool: template
    template: templates/resolvers.ts.jig

  - name: Generate GraphQL context
    tool: template
    template: templates/context.ts.jig

  - name: Instructions
    tool: shell
    command: |
      echo "✅ GraphQL endpoint generated successfully!"
      echo ""
      echo "Created files:"
      echo "  - {{ dir }}/route.ts"
      echo "  - lib/graphql/schema.ts"
      echo "  - lib/graphql/resolvers.ts"
      echo "  - lib/graphql/context.ts"
      echo ""
      echo "GraphQL endpoint:"
      echo "  http://localhost:3000/api/graphql"
      echo ""
      {% if playground %}
      echo "GraphQL Playground (dev only):"
      echo "  http://localhost:3000/api/graphql"
      echo ""
      {% endif %}
      echo "Example query:"
      echo "  query {"
      echo "    hello"
      echo "  }"
      echo ""
      echo "Next steps:"
      echo "  1. Define your GraphQL schema in lib/graphql/schema.ts"
      echo "  2. Implement resolvers in lib/graphql/resolvers.ts"
      {% if auth %}echo "  3. Configure authentication in lib/graphql/context.ts"{% endif %}
      echo "  4. Test queries in GraphQL Playground"
      echo ""
      echo "Learn more:"
      echo "  https://the-guild.dev/graphql/yoga-server/docs"
