name: revalidate
description: |
  Generate a Server Action with cache revalidation patterns.
  Includes revalidatePath, revalidateTag, and optimistic update examples.
version: 1.0.0

variables:
  name:
    type: string
    description: Action name in camelCase (e.g. "createPost", "updateUser")
    required: true
    pattern: "^[a-z][a-zA-Z0-9]*$"

  fields:
    type: array
    description: |
      Form fields in format "name:type:validation" (e.g. "title:string:min(5)")
      Supports same format as add-validated recipe
    required: true

  revalidationType:
    type: string
    description: Type of cache revalidation (path, tag, both)
    default: "both"
    enum: ["path", "tag", "both"]

  revalidatePath:
    type: string
    description: Path to revalidate (e.g. "/posts", "/dashboard")
    required: false

  revalidateTags:
    type: array
    description: Cache tags to revalidate (e.g. ["posts", "user-posts"])
    required: false

  dir:
    type: string
    description: Output directory for Server Action
    default: "app/actions"

  schemaDir:
    type: string
    description: Output directory for Zod schema
    default: "lib/schemas"

  withOptimistic:
    type: boolean
    description: Include optimistic update example in documentation
    default: false

  redirectAfter:
    type: boolean
    description: Redirect after successful action
    default: false

  redirectPath:
    type: string
    description: Path to redirect to after success
    required: false

steps:
  - name: Check Zod dependency
    tool: shell
    command: |
      if ! bun pm ls zod &>/dev/null && ! npm list zod &>/dev/null; then
        echo "Installing zod..."
        if command -v bun &> /dev/null; then
          bun add zod
        elif command -v pnpm &> /dev/null; then
          pnpm add zod
        elif command -v yarn &> /dev/null; then
          yarn add zod
        else
          npm install zod
        fi
      fi

  - name: Create directories
    tool: shell
    command: |
      mkdir -p {{ dir }}
      mkdir -p {{ schemaDir }}

  - name: Generate Zod schema
    tool: template
    template: templates/schema.ts.jig

  - name: Generate Server Action
    tool: template
    template: templates/action.ts.jig

  - name: Instructions
    tool: shell
    command: |
      echo "✅ Server Action with cache revalidation generated!"
      echo ""
      echo "Created files:"
      echo "  - {{ dir }}/{{ name }}.ts"
      echo "  - {{ schemaDir }}/{{ kebabCase(name) }}.ts"
      echo ""
      echo "Cache revalidation strategy:"
@if(revalidationType === 'path' || revalidationType === 'both')
@if(revalidatePath)
      echo "  ✓ Path revalidation: {{ revalidatePath }}"
@else
      echo "  ✓ Path revalidation enabled (configure in action)"
@end
@end
@if(revalidationType === 'tag' || revalidationType === 'both')
@if(revalidateTags && revalidateTags.length > 0)
      echo "  ✓ Tag revalidation: {{ revalidateTags.join(', ') }}"
@else
      echo "  ✓ Tag revalidation enabled (configure in action)"
@end
@end
      echo ""
      echo "Usage with useActionState:"
      echo "  import { useActionState } from 'react'"
      echo "  import { {{ name }} } from '@/{{ dir }}/{{ name }}'"
      echo ""
      echo "  const [state, formAction] = useActionState({{ name }}, null)"
@if(withOptimistic)
      echo ""
      echo "Optimistic updates:"
      echo "  import { useOptimistic } from 'react'"
      echo ""
      echo "  const [optimisticData, addOptimistic] = useOptimistic("
      echo "    data,"
      echo "    (state, newItem) => [...state, newItem]"
      echo "  )"
@end
      echo ""
      echo "Next.js cache will be automatically revalidated on success."
