name: graphql
description: |
  Generate a basic GraphQL endpoint using GraphQL Yoga.
  Provides a foundation for GraphQL APIs with schema-first development.
version: 1.0.0

variables:
  dir:
    type: string
    description: Output directory for GraphQL endpoint
    default: "app/api/graphql"

  playground:
    type: boolean
    description: Enable GraphQL Playground in development
    default: true

  auth:
    type: boolean
    description: Add authentication context
    default: false

steps:
  - name: Install GraphQL dependencies
    tool: install
    packages: [graphql, graphql-yoga]
    optional: true

  - name: Generate GraphQL route handler
    tool: template
    template: templates/route.ts.jig

  - name: Generate GraphQL schema
    tool: template
    template: templates/schema.ts.jig

  - name: Generate GraphQL resolvers
    tool: template
    template: templates/resolvers.ts.jig

  - name: Generate GraphQL context
    tool: template
    template: templates/context.ts.jig

onSuccess: |
  GraphQL endpoint generated successfully!

  Created files:
    - {{ dir }}/route.ts
    - lib/graphql/schema.ts
    - lib/graphql/resolvers.ts
    - lib/graphql/context.ts

  GraphQL endpoint:
    http://localhost:3000/api/graphql
  @if(playground)

  GraphQL Playground (dev only):
    http://localhost:3000/api/graphql
  @end

  Example query:
    query {
      hello
    }

  Next steps:
    1. Define your GraphQL schema in lib/graphql/schema.ts
    2. Implement resolvers in lib/graphql/resolvers.ts
  @if(auth)
    3. Configure authentication in lib/graphql/context.ts
  @end
    4. Test queries in GraphQL Playground

  Learn more:
    https://the-guild.dev/graphql/yoga-server/docs
