name: crud
description: |
  Generate a create/edit form from database model with ORM integration.
  Auto-detects Prisma or Drizzle schema and generates type-safe forms.
version: 1.0.0

variables:
  model:
    type: string
    description: Database model name (e.g. "User", "Post", "Product")
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  dir:
    type: string
    description: Output directory for form component
    default: "components/forms"

  actionPath:
    type: string
    description: Path to Server Actions directory
    default: "app/actions"

  fields:
    type: array
    description: |
      Optional: Specific fields to include (comma-separated).
      If not provided, all non-relation fields are included.
      Example: "name,email,bio"
    required: false

  excludeFields:
    type: array
    description: |
      Fields to exclude from form (comma-separated).
      Common: "id,createdAt,updatedAt"
    default: ["id", "createdAt", "updatedAt"]

  mode:
    type: string
    description: Form mode - 'create', 'edit', or 'both'
    default: "both"
    pattern: "^(create|edit|both)$"

  withServerAction:
    type: boolean
    description: Generate Server Actions for create/update
    default: true

steps:
  - name: Detect ORM
    tool: shell
    command: |
      # Detect which ORM is being used
      if [ -f "prisma/schema.prisma" ]; then
        echo "DETECTED_ORM=prisma" > .hypergen-temp
      elif [ -d "db/schema" ] || [ -f "db/schema.ts" ]; then
        echo "DETECTED_ORM=drizzle" > .hypergen-temp
      else
        echo "❌ Error: No ORM detected. Please set up Prisma or Drizzle first."
        echo "Run: hypergen nextjs database prisma-init"
        echo "Or:  hypergen nextjs database drizzle-init"
        exit 1
      fi

  - name: Check dependencies
    tool: shell
    command: |
      # Install Zod if not present
      if ! bun pm ls zod &>/dev/null; then
        echo "Installing Zod for validation..."
        if command -v bun &> /dev/null; then
          bun add zod
        elif command -v pnpm &> /dev/null; then
          pnpm add zod
        elif command -v yarn &> /dev/null; then
          yarn add zod
        else
          npm install zod
        fi
      fi

      # Check if shadcn/ui Form component is installed
      if [ ! -f "components/ui/form.tsx" ]; then
        echo "Installing shadcn/ui Form component..."
        npx shadcn@latest add form --yes
      fi

  - name: Create directories
    tool: shell
    command: |
      mkdir -p {{ dir }}
      mkdir -p lib/schemas
@if(withServerAction)
      mkdir -p {{ actionPath }}
@end

  - name: Generate schema
    tool: template
    template: templates/schema.ts.jig

  - name: Generate form component
    tool: template
    template: templates/form.tsx.jig

@if(withServerAction)
  - name: Generate create action
    tool: template
    template: templates/create-action.ts.jig
    condition: "{{ mode === 'create' || mode === 'both' }}"

  - name: Generate update action
    tool: template
    template: templates/update-action.ts.jig
    condition: "{{ mode === 'edit' || mode === 'both' }}"
@end

  - name: Cleanup
    tool: shell
    command: rm -f .hypergen-temp

  - name: Instructions
    tool: shell
    command: |
      echo "✅ CRUD form generated successfully!"
      echo ""
      echo "Created files:"
      echo "  - {{ dir }}/{{ model }}Form.tsx"
      echo "  - lib/schemas/{{ kebabCase(model) }}-schema.ts"
@if(withServerAction)
@if(mode === 'both' || mode === 'create')
      echo "  - {{ actionPath }}/create-{{ kebabCase(model) }}.ts"
@end
@if(mode === 'both' || mode === 'edit')
      echo "  - {{ actionPath }}/update-{{ kebabCase(model) }}.ts"
@end
@end
      echo ""
      echo "Usage:"
      echo ""
      echo "Create mode:"
      echo "  import { {{ model }}Form } from '@/{{ dir }}/{{ model }}Form'"
      echo "  "
      echo "  <{{ model }}Form mode=\"create\" />"
      echo ""
      echo "Edit mode:"
      echo "  import { {{ model }}Form } from '@/{{ dir }}/{{ model }}Form'"
      echo "  "
      echo "  <{{ model }}Form mode=\"edit\" initialData={existing{{ model }}} />"
