// @hypercli/drive - Hyperdrive: spaces, warp, and machine sync for the hyper CLI
export {
	ConfigError,
	configExists,
	configPath,
	type DeepPartial,
	loadConfig,
	readRawConfig,
	writeConfig,
} from "#config/index";
export {
	CLAUDE_SYNC_IGNORE,
	DEFAULT_CONFIG,
	DEFAULT_MACHINE,
	type DriveConfig,
	EMPTY_MANIFEST,
	isValidSpaceName,
	type Manifest,
	ManifestError,
	PI_SYNC_IGNORE,
	packagedSyncIgnore,
	SPACE_NAME_PATTERN,
	type SpaceEntry,
	type SpaceRepo,
	type SyncCadence,
	type SyncTarget,
	syncIgnoreFor,
	validateManifest,
} from "#config/schema";
export { type BaseArgs, BaseCommand, type BaseFlags } from "#lib/base-command";
export {
	ALLOWLIST_MARKER,
	AllowlistError,
	findSecretPaths,
	isHyperAllowlist,
	normaliseTrackedEntry,
	RESERVED_PATHS,
	renderGitignore,
	SECRET_PATTERNS,
} from "#services/allowlist";
export {
	addHint,
	listHerdrMachines,
	listMachines,
	MachineError,
	type MachineInfo,
	type MachineSource,
	resolveMachine,
	runnerFor,
	self,
} from "#services/machine";
export {
	assembleRootScript,
	type RootScriptEntry,
	RootScriptError,
	remoteScriptPath,
} from "#services/machine/root-script";
export {
	ROOT_SCRIPT_NAME,
	type RootChoice,
	type RootQuestion,
	type RunSetupOptions,
	runSetup,
	type SetupPrompt,
	type SetupReport,
} from "#services/machine/runner";
export {
	FEATURE_LIST,
	FEATURES,
	type Feature,
	isFeature,
	type Task,
	type TaskContext,
	TaskError,
} from "#services/machine/tasks/types";
export {
	driveCheckoutDir,
	driveCheckoutOrigin,
	ensureDriveCheckout,
	readManifest,
	removeSpace,
	upsertSpace,
} from "#services/manifest";
export {
	exitCodeForSignal,
	isExcluded,
	LocalMachine,
	type MachineRunner,
	RemoteError,
	RemoteMachine,
	RemotePathError,
	type RsyncOptions,
	type RunResult,
	remoteSpec,
	type Spawner,
	type SpawnRequest,
	type SshOptions,
	shellJoin,
	shellQuote,
} from "#services/remote";
export {
	claudeHome,
	encodeProjectDir,
	type LiveOptions,
	type LiveSession,
	lastAssistantText,
	latestTranscript,
	listTranscripts,
	liveSession,
	liveSessions,
	liveSessionsFor,
	type OwnerMarker,
	type OwnerState,
	ownerPath,
	projectDir,
	readOwner,
	type StopOutcome,
	stopSession,
	type TranscriptRef,
	transcriptLineCount,
	VERIFIED_CLAUDE_VERSION,
	writeOwner,
} from "#services/sessions";
export {
	detectSpace,
	findSpaceRoot,
	isSpace,
	libPath,
	repoSlugOf,
	type SpaceInfo,
	type SpaceLayout,
	spaceLayout,
	spaceRepos,
	worktreesDir,
} from "#services/space";
export {
	hasSpaceGit,
	type InitSpaceGitOptions,
	type InitSpaceGitResult,
	initSpaceGitDir,
	type ProjectRepoInfo,
	projectRepoInfo,
	readCadence,
	readSpaceBlobPrefixes,
	readSpaceConfig,
	readStagedBlobPrefix,
	readTracked,
	removeSpaceGitDir,
	type SpaceBlobPrefix,
	SpaceGitError,
	SpaceGitInterruptedError,
	type SpaceGitOptions,
	type SpaceGitResult,
	spaceGit,
	spaceGitDir,
	writeCadence,
	writeTracked,
} from "#services/space-git";
export {
	fetchSpace,
	type InitializedSpace,
	logSpace,
	pullSpace,
	requireInitializedSpace,
	type SpaceStatusEntry,
	spaceRemote,
	spaceStatus,
	withSpaceSignals,
} from "#services/space-history";
export {
	type IncomingSpaceValidation,
	SpaceIncomingError,
	validateIncomingSpace,
} from "#services/space-incoming";
export {
	commitAndPushSpace,
	commitSpace,
	hookReason,
	inspectStagedFiles,
	pushSpace,
	remoteRef,
	remoteSha,
	type SpaceCommitResult,
	SpacePushRefusedError,
	spaceGitRemote,
	stagedGitlinks,
	stagedPaths,
} from "#services/space-sync";
export {
	getEngine,
	type SyncCreateOptions,
	type SyncDaemonState,
	type SyncEngine,
	SyncEngineError,
	type SyncEngineName,
	type SyncMode,
	type SyncSession,
	type SyncSymlinkMode,
} from "#services/sync/engine";
export {
	createArgs,
	daemonRegistered,
	MutagenSyncEngine,
	parseSessionList,
} from "#services/sync/mutagen";
