name: validated
description: |
  Generate a Server Action with Zod validation.
  Includes type-safe formData extraction, field-level errors, and schema validation.
version: 1.0.0

variables:
  name:
    type: string
    description: Action name in camelCase (e.g. "createUser", "updateProfile")
    required: true
    pattern: "^[a-z][a-zA-Z0-9]*$"

  fields:
    type: array
    description: |
      Form fields in format "name:type:validation" (e.g. "email:string:email", "age:number:min(18)")
      Supported types: string, number, boolean, date, enum
      Validations: email, url, min(n), max(n), length(n), optional, array
    required: true

  dir:
    type: string
    description: Output directory for Server Action
    default: "app/actions"

  schemaDir:
    type: string
    description: Output directory for Zod schema
    default: "lib/schemas"

  withPrevState:
    type: boolean
    description: Add prevState parameter for useActionState hook
    default: true

  returnPath:
    type: string
    description: Path to redirect/revalidate after success (optional)
    required: false

steps:
  - name: Install Zod
    tool: install
    packages: [zod]

  - name: Generate Zod schema
    tool: template
    template: templates/schema.ts.jig

  - name: Generate Server Action
    tool: template
    template: templates/action.ts.jig

onSuccess: |
  Validated Server Action generated successfully!

  Created files:
    - {{ dir }}/{{ name }}.ts
    - {{ schemaDir }}/{{ kebabCase(name) }}.ts

  Usage with useActionState:
    'use client'
    import { useActionState } from 'react'
    import { {{ name }} } from '@/{{ dir }}/{{ name }}'

    export function MyForm() {
      const [state, formAction, pending] = useActionState({{ name }}, null)

      return (
        <form action={formAction}>
          {/* Field-level error display */}
          {state?.errors?.fieldName && (
            <p className="text-red-500">{state.errors.fieldName[0]}</p>
          )}
          <button disabled={pending}>Submit</button>
        </form>
      )
    }

  The schema is also exported and can be reused:
    import { {{ camelCase(name) }}Schema } from '@/{{ schemaDir }}/{{ kebabCase(name) }}'
