name: add
description: |
  Add an error boundary to a Next.js App Router route segment.
  Creates error.tsx that catches errors in the segment and displays a fallback UI.
version: 1.0.0

variables:
  path:
    type: string
    description: Route segment path relative to app/ (e.g. "dashboard", "blog/[slug]")
    required: true

  withReset:
    type: boolean
    description: Include a retry/reset button
    default: true

  withNotFound:
    type: boolean
    description: Also generate a not-found.tsx for this segment
    default: false

steps:
  - name: Generate error boundary
    tool: template
    template: templates/error.tsx.jig

  - name: Generate not-found page
    tool: template
    template: templates/not-found.tsx.jig
    when: "withNotFound === true"
