name: basic
description: |
  Generate a basic Server Action with FormData handling.
  Perfect for simple form submissions without complex validation.
version: 1.0.0

variables:
  name:
    type: string
    description: Action name in camelCase (e.g. "createUser", "updateProfile")
    required: true
    pattern: "^[a-z][a-zA-Z0-9]*$"

  fields:
    type: array
    description: |
      Form fields in format "name:type" (e.g. "email:string", "age:number")
      Supported types: string, number, boolean, date
    required: true

  dir:
    type: string
    description: Output directory for Server Action
    default: "app/actions"

  withPrevState:
    type: boolean
    description: Add prevState parameter for useActionState hook
    default: true

  returnPath:
    type: string
    description: Path to redirect/revalidate after success (optional)
    required: false

steps:
  - name: Create actions directory
    tool: shell
    command: mkdir -p {{ dir }}

  - name: Generate Server Action
    tool: template
    template: templates/action.ts.jig

  - name: Instructions
    tool: shell
    command: |
      echo "✅ Server Action generated successfully!"
      echo ""
      echo "Created file:"
      echo "  - {{ dir }}/{{ name }}.ts"
      echo ""
      echo "Usage with useActionState:"
      echo "  'use client'"
      echo "  import { useActionState } from 'react'"
      echo "  import { {{ name }} } from '@/{{ dir }}/{{ name }}'"
      echo ""
      echo "  export function MyForm() {"
      echo "    const [state, formAction, pending] = useActionState({{ name }}, null)"
      echo ""
      echo "    return ("
      echo "      <form action={formAction}>"
      echo "        {/* form fields */}"
      echo "        <button disabled={pending}>Submit</button>"
      echo "        {state?.error && <p>{state.error}</p>}"
      echo "      </form>"
      echo "    )"
      echo "  }"
      echo ""
      echo "Usage with plain form:"
      echo "  <form action={{{ name }}}>"
      echo "    {/* form fields */}"
      echo "  </form>"
