name: basic
description: |
  Generate a basic Server Action with FormData handling.
  Perfect for simple form submissions without complex validation.
version: 1.0.0

variables:
  name:
    type: string
    description: Action name in camelCase (e.g. "createUser", "updateProfile")
    required: true
    pattern: "^[a-z][a-zA-Z0-9]*$"

  fields:
    type: array
    description: |
      Form fields in format "name:type" (e.g. "email:string", "age:number")
      Supported types: string, number, boolean, date
    required: true

  dir:
    type: string
    description: Output directory for Server Action
    default: "app/actions"

  withPrevState:
    type: boolean
    description: Add prevState parameter for useActionState hook
    default: true

  returnPath:
    type: string
    description: Path to redirect/revalidate after success (optional)
    required: false

onSuccess: |
  Server Action generated successfully!

  Created file:
    - {{ dir }}/{{ name }}.ts

  Usage with useActionState:
    'use client'
    import { useActionState } from 'react'
    import { {{ name }} } from '@/{{ dir }}/{{ name }}'

    export function MyForm() {
      const [state, formAction, pending] = useActionState({{ name }}, null)

      return (
        <form action={formAction}>
          {/* form fields */}
          <button disabled={pending}>Submit</button>
          {state?.error && <p>{state.error}</p>}
        </form>
      )
    }

  Usage with plain form:
    <form action={ {{ name }} }>
      {/* form fields */}
    </form>

steps:
  - name: Generate Server Action
    tool: template
    template: templates/action.ts.jig
