name: route
description: |
  Generate a REST API endpoint with type-safe request/response handling.
  Supports GET, POST, PUT, PATCH, DELETE methods with optional Zod validation,
  authentication, and ORM integration.
version: 1.0.0

variables:
  name:
    type: string
    description: Route name in kebab-case (e.g. "users", "blog-posts")
    required: true
    pattern: "^[a-z][a-z0-9-]*$"

  methods:
    type: array
    description: |
      HTTP methods to support (e.g. ["GET", "POST"])
      Supported: GET, POST, PUT, PATCH, DELETE
    required: true
    default: ["GET", "POST"]

  auth:
    type: boolean
    description: Add authentication check using detected auth provider
    default: false

  validation:
    type: boolean
    description: Add Zod validation schemas for POST/PUT/PATCH
    default: true

  cors:
    type: boolean
    description: Add CORS headers for external API access
    default: false

  dir:
    type: string
    description: Output directory for API route
    default: "app/api"

steps:
  - name: Detect project features
    tool: shell
    command: |
      echo "Detecting ORM and auth provider..."

  - name: Generate route handler
    tool: template
    template: templates/route.ts.jig

  - name: Generate validation schemas
    tool: template
    template: templates/schemas.ts.jig
    when: "{{ validation }}"

onSuccess: |
  API route generated successfully!

  Created files:
    - {{ dir }}/{{ name }}/route.ts
  @if(validation)
    - lib/schemas/api-{{ name }}-schema.ts
  @end

  Supported methods: {{ methods | join: ', ' }}
  @if(auth)
  Authentication: Enabled
  @end
  @if(cors)
  CORS: Enabled
  @end

  Test your API:
    curl http://localhost:3000/api/{{ name }}
  @if(methods.includes('POST'))

    curl -X POST http://localhost:3000/api/{{ name }} \
      -H 'Content-Type: application/json' \
      -d '{"name":"test"}'
  @end

  Next steps:
    1. Update the response types in route.ts
    2. Implement database queries using your ORM
  @if(validation)
    3. Customize validation schemas in lib/schemas/api-{{ name }}-schema.ts
  @end
  @if(auth)
    4. Configure authentication middleware
  @end
