name: resource
description: |
  Generate a complete full-stack CRUD resource by orchestrating all granular recipes.
  This flagship "meta-recipe" calls list-page, detail-page, create-page, edit-page, and delete recipes.

  Generated files (8-12 depending on ORM):
  - List page with data table (sorting, filtering, pagination)
  - Detail view page with delete dialog
  - Create page with form
  - Edit page with pre-filled form
  - All Server Actions (list, create, read, update, delete)
  - Zod validation schema
  - Reusable table and form components

  Time saved: 60-120 min → 5 min (12-24x faster)

version: 2.0.0

variables:
  name:
    type: string
    description: Resource name (singular, e.g., 'post', 'user', 'product')
    required: true
    position: 0
    prompt: What is the resource name? (singular, e.g., 'post', 'user')

  model:
    type: string
    description: Model name (PascalCase, defaults to capitalized name)
    required: false

  fields:
    type: string
    description: Comma-separated fields with types (e.g., "title:string,content:text,published:boolean")
    required: false
    prompt: |
      Enter fields (comma-separated, format: name:type)
      Leave empty to auto-detect from Prisma/Drizzle schema
      Example: title:string,content:text,published:boolean

  pages:
    type: enum
    multiple: true
    values: ['list', 'detail', 'create', 'edit']
    default: ['list', 'detail', 'create', 'edit']
    description: Which pages to generate (AI can override when --ask=ai)

  useServerActions:
    type: boolean
    description: Use Server Actions instead of API routes
    default: true

  includePagination:
    type: boolean
    description: Include pagination in list view
    default: true

  includeSorting:
    type: boolean
    description: Include sorting in data table
    default: true

  includeFiltering:
    type: boolean
    description: Include filtering in data table
    default: true

  includeDelete:
    type: boolean
    description: Include delete functionality with confirmation dialog
    default: true

steps:
  - name: Generate list page with data table
    tool: recipe
    recipe: ../list-page
    when: "pages.includes('list')"
    args:
      name: "{{ name }}"
      model: "{{ model }}"
      fields: "{{ fields }}"
      includePagination: "{{ includePagination }}"
      includeSorting: "{{ includeSorting }}"
      includeFiltering: "{{ includeFiltering }}"

  - name: Generate detail page
    tool: recipe
    recipe: ../detail-page
    when: "pages.includes('detail')"
    args:
      name: "{{ name }}"
      model: "{{ model }}"
      includeDelete: "{{ includeDelete }}"

  - name: Generate create page with form
    tool: recipe
    recipe: ../create-page
    when: "pages.includes('create')"
    args:
      name: "{{ name }}"
      model: "{{ model }}"
      fields: "{{ fields }}"

  - name: Generate edit page
    tool: recipe
    recipe: ../edit-page
    when: "pages.includes('edit')"
    args:
      name: "{{ name }}"
      model: "{{ model }}"
      fields: "{{ fields }}"

  - name: Install zod
    tool: install
    packages: [zod]
    optional: true

  - name: Install react-hook-form
    tool: install
    packages: [react-hook-form, "@hookform/resolvers"]
    optional: true

onSuccess: |
  Complete CRUD resource '{{ name }}' generated successfully!

  This meta-recipe orchestrated 4 granular recipes:
    1. list-page - List view with data table
    2. detail-page - Detail view with actions
    3. create-page - Create form with validation
    4. edit-page - Edit form with pre-fill

  Generated files:
    app/{{ name }}/page.tsx - List view
    app/{{ name }}/[id]/page.tsx - Detail view
    app/{{ name }}/[id]/edit/page.tsx - Edit page
    app/{{ name }}/new/page.tsx - Create page
    components/{{ model || name }}Table.tsx - Data table
    components/{{ model || name }}Form.tsx - Create/edit form
  @if(includeDelete)
    components/{{ model || name }}DeleteDialog.tsx - Delete confirmation
  @end
    app/actions/{{ name }}.ts - All CRUD Server Actions
    lib/schemas/{{ name }}-schema.ts - Validation

  Next steps:
    1. Review and customize the generated files
  @if(fields)
    2. Update your database schema and run migrations
  @else
    2. Make sure your database model matches the schema
  @end
    3. Visit /{{ name }} to see your CRUD interface

  Time saved: ~90 minutes
