name: nextjs
description: Scaffold a new Next.js project with Tailwind CSS, TypeScript, and optional AI-powered customization
version: 1.0.0

variables:
  name:
    type: string
    description: Project name (used as directory name and in package.json)
    required: true
    pattern: "^[a-z][a-z0-9-]*$"

  description:
    type: string
    description: Short project description
    default: "A Next.js application"

  useSrcDir:
    type: boolean
    description: Use a src/ directory for source files
    default: false

  linter:
    type: enum
    description: Which linter/formatter to use
    values: [eslint, biome, none]
    default: eslint

steps:
  - name: Scaffold Next.js Project
    tool: recipe
    recipe: cookbooks/project/create/recipe.yml
    variables:
      name: "{{ name }}"
      description: "{{ description }}"
      useSrcDir: "{{ useSrcDir }}"
      linter: "{{ linter }}"

  - name: Install Dependencies
    tool: shell
    command: cd {{ name }} && bun install
