name: server
description: |
  Generate a TanStack Table with server-side pagination, sorting, and filtering.
  Includes loading states, URL query params, and API integration.
version: 1.0.0

variables:
  name:
    type: string
    description: Table component name in PascalCase
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  columns:
    type: array
    description: Table columns in format "key:label:type:sortable:filterable"
    required: true

  apiEndpoint:
    type: string
    description: API endpoint for data (e.g. "/api/users")
    required: true

  dir:
    type: string
    description: Output directory
    default: "components/tables"

  pageSize:
    type: number
    description: Default page size
    default: 10

steps:
  - name: Check dependencies
    tool: shell
    command: |
      if ! bun pm ls @tanstack/react-table &>/dev/null; then
        bun add @tanstack/react-table 2>/dev/null || npm install @tanstack/react-table
      fi

      if ! bun pm ls @tanstack/react-query &>/dev/null; then
        bun add @tanstack/react-query 2>/dev/null || npm install @tanstack/react-query
      fi

      if [ ! -f "components/ui/table.tsx" ]; then
        npx shadcn@latest add table --yes
      fi

      if [ ! -f "components/ui/skeleton.tsx" ]; then
        npx shadcn@latest add skeleton --yes
      fi

  - name: Create output directory
    tool: shell
    command: mkdir -p {{ dir }}

  - name: Generate types
    tool: template
    template: templates/types.ts.jig

  - name: Generate API hook
    tool: template
    template: templates/use-data.ts.jig

  - name: Generate columns
    tool: template
    template: templates/columns.tsx.jig

  - name: Generate server table
    tool: template
    template: templates/table.tsx.jig

  - name: Instructions
    tool: shell
    command: |
      echo "✅ Server-side data table generated!"
      echo ""
      echo "Features:"
      echo "  ✓ Server-side pagination"
      echo "  ✓ Server-side sorting"
      echo "  ✓ Server-side filtering"
      echo "  ✓ Loading states"
      echo "  ✓ URL query params"
      echo ""
      echo "API endpoint: {{ apiEndpoint }}"
      echo ""
      echo "Expected API response format:"
      echo "{"
      echo "  \"data\": [],        // Array of rows"
      echo "  \"total\": 100,      // Total count"
      echo "  \"page\": 1,         // Current page"
      echo "  \"pageSize\": 10     // Page size"
      echo "}"
