name: webhook
description: |
  Generate webhook handlers with signature verification for external services.
  Supports common providers (Stripe, GitHub, Shopify) with built-in verification.
version: 1.0.0

variables:
  name:
    type: string
    description: Webhook name in kebab-case (e.g. "stripe", "github")
    required: true
    pattern: "^[a-z][a-z0-9-]*$"

  provider:
    type: string
    description: |
      Pre-configured provider (optional)
      Supported: stripe, github, shopify, clerk, resend
    required: false
    default: "custom"

  verification:
    type: boolean
    description: Add signature verification (recommended for security)
    default: true

  dir:
    type: string
    description: Output directory for webhook handler
    default: "app/api/webhooks"

steps:
  - name: Generate webhook handler
    tool: template
    template: templates/webhook-route.ts.jig

  - name: Generate signature verifier
    tool: template
    template: templates/verifier.ts.jig
    when: "{{ verification }}"

onSuccess: |
  Webhook handler generated successfully!

  Created files:
    - {{ dir }}/{{ name }}/route.ts
  @if(verification)
    - lib/webhooks/{{ name }}-verifier.ts
  @end

  Provider: {{ provider }}

  Webhook URL:
    https://yourdomain.com/api/webhooks/{{ name }}

  Required environment variables:
  @if(provider === 'stripe')
    STRIPE_WEBHOOK_SECRET=whsec_...
  @else if(provider === 'github')
    GITHUB_WEBHOOK_SECRET=your_secret
  @else if(provider === 'shopify')
    SHOPIFY_WEBHOOK_SECRET=your_secret
  @else if(provider === 'clerk')
    CLERK_WEBHOOK_SECRET=whsec_...
  @else if(provider === 'resend')
    RESEND_WEBHOOK_SECRET=your_secret
  @else if(verification)
    {{ name | upper }}_WEBHOOK_SECRET=your_secret
  @end

  Next steps:
    1. Add the webhook secret to your .env.local
    2. Configure the webhook in your provider's dashboard
    3. Implement event handlers in the route file
    4. Test using the provider's CLI or test mode
  @if(provider === 'stripe')

  Test with Stripe CLI:
    stripe listen --forward-to localhost:3000/api/webhooks/{{ name }}
  @end
