name: basic
description: |
  Generate a basic TanStack Table with client-side pagination.
  Includes column definitions, type-safe data handling, and shadcn/ui styling.
version: 1.0.0

variables:
  name:
    type: string
    description: Table component name in PascalCase (e.g. "UsersTable", "ProductsTable")
    required: true
    pattern: "^[A-Z][a-zA-Z0-9]*$"

  columns:
    type: array
    description: |
      Table columns in format "key:label:type" (e.g. "id:ID:string", "email:Email:string", "age:Age:number")
      Supported types: string, number, boolean, date
    required: true

  dir:
    type: string
    description: Output directory for table component
    default: "components/tables"

  withPagination:
    type: boolean
    description: Include pagination controls
    default: true

  pageSize:
    type: number
    description: Default page size
    default: 10

steps:
  - name: Check dependencies
    tool: shell
    command: |
      # Check if required packages are installed
      if ! bun pm ls @tanstack/react-table &>/dev/null; then
        echo "Installing required dependencies..."
        if command -v bun &> /dev/null; then
          bun add @tanstack/react-table
        elif command -v pnpm &> /dev/null; then
          pnpm add @tanstack/react-table
        elif command -v yarn &> /dev/null; then
          yarn add @tanstack/react-table
        else
          npm install @tanstack/react-table
        fi
      fi

      # Check if shadcn/ui Table component is installed
      if [ ! -f "components/ui/table.tsx" ]; then
        echo "Installing shadcn/ui Table component..."
        npx shadcn@latest add table --yes
      fi

      # Install Button if pagination is enabled
      if [ "{{ withPagination }}" = "true" ] && [ ! -f "components/ui/button.tsx" ]; then
        echo "Installing shadcn/ui Button component..."
        npx shadcn@latest add button --yes
      fi

  - name: Create output directory
    tool: shell
    command: mkdir -p {{ dir }}

  - name: Generate TypeScript types
    tool: template
    template: templates/types.ts.jig

  - name: Generate column definitions
    tool: template
    template: templates/columns.tsx.jig

  - name: Generate table component
    tool: template
    template: templates/table.tsx.jig

  - name: Instructions
    tool: shell
    command: |
      echo "✅ Data table generated successfully!"
      echo ""
      echo "Created files:"
      echo "  - {{ dir }}/{{ name }}.tsx"
      echo "  - {{ dir }}/columns.tsx"
      echo "  - lib/types/{{ kebabCase(name) }}.ts"
      echo ""
      echo "Usage:"
      echo "  import { {{ name }} } from '@/{{ dir }}/{{ name }}'"
      echo ""
      echo "  export default function Page() {"
      echo "    const data = [] // Your data array"
      echo "    return <{{ name }} data={data} />"
      echo "  }"
      echo ""
      echo "Next steps:"
      echo "  - Add sorting: hypergen nextjs table sortable"
      echo "  - Add filtering: hypergen nextjs table filterable"
      echo "  - Add server features: hypergen nextjs table server"
