#!/usr/bin/env bash
set -eo pipefail

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

# Fix: Convert relative GIT_INDEX_FILE to absolute path
# When git runs hooks, it sets GIT_INDEX_FILE=.git/index (relative)
# This breaks when moon runs git commands from subdirectories
if [ -n "$GIT_INDEX_FILE" ] && [ "${GIT_INDEX_FILE:0:1}" != "/" ]; then
  export GIT_INDEX_FILE="$(pwd)/$GIT_INDEX_FILE"
fi

moon run :lint :format --affected --status=staged

